import pygame
# группа со спрайтами
all_sprites = pygame.sprite.Group()
bullet_sprites = pygame.sprite.Group()

attack_group = pygame.sprite.Group()
enemy_attack_group = pygame.sprite.Group()

# Спрайты персов
aksenov = pygame.image.load(r"assets\images\main hero\Sprites\aksenov.png").convert_alpha()
lisa = pygame.image.load(r"assets\images\main hero\Sprites\lisa.png").convert_alpha()
soldier = pygame.image.load(r"assets\images\main hero\Sprites\soldier.png").convert_alpha()
yacugi = pygame.image.load(r"assets\images\main hero\Sprites\yakugi.png").convert_alpha()
soldier_japan = pygame.image.load(r"assets\images\main hero\Sprites\japanese_soldier.png").convert_alpha()
police = pygame.image.load(r"assets\images\main hero\Sprites\police.png").convert_alpha()
negrominator = pygame.image.load(r"assets\images\main hero\Sprites\negrominator.png").convert_alpha()
artestro = pygame.image.load(r"assets\images\main hero\Sprites\artestro.png").convert_alpha()
general = pygame.image.load(r"assets\images\main hero\Sprites\generall.png").convert_alpha()
super_pau = pygame.image.load(r"assets\images\main hero\Sprites\SUPERPAUK.png").convert_alpha()
super_pau_boss = pygame.image.load(r"assets\images\main hero\Sprites\Superpau.png").convert_alpha()
SUPER_PAU = pygame.image.load(r"assets\images\main hero\Sprites\SUPER_PAU.png").convert_alpha()
bt25t = pygame.image.load(r"assets\images\main hero\Sprites\bt.png").convert_alpha()
moiseev = pygame.image.load(r"assets\images\main hero\Sprites\moiseev.png").convert_alpha()
tagir = pygame.image.load(r"assets\images\main hero\Sprites\tagir.png").convert_alpha()
egor = pygame.image.load(r"assets\images\main hero\Sprites\egor.png").convert_alpha()
kingartema = pygame.image.load(r"assets\images\main hero\Sprites\kingartema.png").convert_alpha()
vesisa = pygame.image.load(r"assets\images\main hero\Sprites\vesisa.png").convert_alpha()
bulat = pygame.image.load(r"assets\images\main hero\Sprites\bulat.png").convert_alpha()
robot_woman = pygame.image.load(r"assets\images\main hero\Sprites\robot_womon.png").convert_alpha()
moiseev_security = pygame.image.load(r"assets\images\main hero\Sprites\soldier_mais.png").convert_alpha()
walker = pygame.image.load(r"assets\images\main hero\Sprites\strider.png").convert_alpha()
trio = pygame.image.load(r"assets\images\main hero\Sprites\trio.png").convert_alpha()
supertank = pygame.image.load(r"assets\images\main hero\Sprites\supertank.png").convert_alpha()
albinos = pygame.image.load(r"assets\images\main hero\Sprites\albinos.png").convert_alpha()
moiseev_bot = pygame.image.load(r"assets\images\main hero\Sprites\moiseev_bot.png").convert_alpha()

super_pau_2 = pygame.image.load(r"assets\images\main hero\Sprites_2\SUPER_PAU.png").convert_alpha()
lisa_2 = pygame.image.load(r"assets\images\main hero\Sprites_2\lisa.png").convert_alpha()
# партиклы
blood = pygame.image.load(r"assets\images\main hero\particles\blood.png").convert_alpha()
electricity = pygame.image.load(r"assets\images\main hero\particles\electrisity.png").convert_alpha()
bt_parts = pygame.image.load(r"assets\images\main hero\particles\bt_parts.png").convert_alpha()
dumplings = pygame.image.load(r"assets\images\main hero\particles\dumpling.png").convert_alpha()
dust = pygame.image.load(r"assets\images\main hero\particles\dust.png").convert_alpha()
shield_parts = pygame.image.load(r"assets\images\main hero\particles\shield_parts.png").convert_alpha()

energy = pygame.image.load(r"assets\images\main hero\particles\energy.png").convert_alpha()
explosion = pygame.image.load(r"assets\images\main hero\particles\explosion.png").convert_alpha()
bullet = pygame.image.load(r"assets\images\main hero\particles\bullet.png").convert_alpha()
beam = pygame.image.load(r"assets\images\main hero\particles\beam.png").convert_alpha()
rocket = pygame.image.load(r"assets\images\main hero\particles\rocket.png").convert_alpha()
stone = pygame.image.load(r"assets\images\main hero\particles\stone.png").convert_alpha()
