import constants.textures.backgrounds as bg

aksenov = (r'assets\images\dialog\dan_dialog.png', "Аксёнов")
aksenov_old = (r'assets\images\dialog\dan_old_dialog.png', "Аксёнов")
moiseev_old = (r'assets\images\dialog\mais_old_dial.png', "Моисеев")
artestro_old = (r'assets\images\dialog\artestro_old_dialog.png', "Артист")
moiseev = (r'assets\images\dialog\mais_dial.png', "Моисеев")
lisa = (r'assets\images\dialog\lisa_dial.png', "Лиза")
artestro = (r'assets\images\dialog\artestro_dialog.png', "Артист")
pau = (r'assets\images\dialog\superpau_dialog.png', "Super PAU")
yakuji = (r"assets\images\dialog\yakuji_dial.png", "Якудза")
soldier = (r"assets\images\dialog\soldier_dial.png", "Солдат")
police = (r"assets\images\dialog\police_dial.png", "Полицейский")
civil = (r"assets\images\dialog\civil_dial.png", "Гражданский")
aks_mech = (r"assets\images\dialog\dan_mech.png", "Аксёнов в Мехе")
negrominator = (r"assets\images\dialog\negrominator_dial.png", "Негроминатор")
general = (r"assets\images\dialog\general_dial.png", "Генерал")
semen = (r"assets\images\dialog\semen_dial.png", "Семён")
kamil = (r"assets\images\dialog\kamil_dial.png", "Камиль")
semen_old = (r"assets\images\dialog\semen_old_dial.png", "Семён")
kamil_old = (r"assets\images\dialog\kamil_old_dial.png", "Камиль")
egor = (r"assets\images\dialog\egor.png", "Егор")
artem = (r"assets\images\dialog\artem.png", "Артём")  # s
tagir = (r"assets\images\dialog\tagir 2.png", "Тагир")
bt25 = (r"assets\images\dialog\bt25.png", "Bt25t")
vasisa = (r"assets\images\dialog\vesisa_dial.png", "Васиса")
USAarmy = (r"assets\images\dialog\soldier_dial.png", "ПехотаСША")    # s
trio = (r"assets\images\dialog\trio.png", "Трое")
albina = (r"assets\images\dialog\albina.png", "Альбина")
bulat = (r"assets\images\dialog\bulat.png", "Булат")
moiseev_ten = (r'assets\images\dialog\maiseev_ten.png', "Моисеев")
tagir_butterfly = (r"assets\images\dialog\tagir 1.png", "Тагир")
artem_old = (r"assets\images\dialog\artem_old.png", "Артём")  # s
dumpling = (r"assets\images\dialog\dumpling.png", "Артём")
adel = (r"assets\images\dialog\adel.png", "Адель")
aynur = (r"assets\images\dialog\aynur.png", "Айнур")
turov = (r"assets\images\dialog\turov.png", "Туров")
president = (r"assets\images\dialog\president.png", "Президент")
minobr = (r"assets\images\dialog\president.png", "МинОброныГос.")
kids = (r"assets\images\dialog\kids.png", "Дети на улице")
moiseev_bot = (r"assets\images\dialog\moiseev_bot.png", "Моисеев Бот")
gos_army = (r"assets\images\dialog\soldier_dial.png", "Государственный Наемник")  # s
bulat_phone = (r"assets\images\dialog\none.png", "Булат")
vasisa_in_sphere = (r"assets\images\dialog\none.png", "Голос Васисы")
question = (r"assets\images\dialog\none.png", "???")
scientist = (r"assets\images\dialog\scientist.png", "Ученый")
stolberg_early = (r"assets\images\dialog\stolberg.png", "Столберг")
stolberg = (r"assets\images\dialog\stolberg_old.png", "Столберг")
vasisa_normal = (r"assets\images\dialog\civil_dial.png", "Васиса")  # s


# (, "", bg.),
def dialogs_texts():
    texts = [
        # 0
        [[], [(None, "... подключено.", bg.lab_mais),
              (moiseev_old, "ABOBA OS работает!", bg.lab_mais),
              (moiseev_old, "Вы должны были стать теми, о ком вы сейчас думали", bg.lab_mais),
              (semen_old, "Странно, но я совсем не о этом думал", bg.lab_mais),
              (semen_old, "Я даже не знаю кем я стал", bg.lab_mais),
              (moiseev_old, "хм, похоже, что мне придется вас проверить на функционал.", bg.lab_mais),
              (moiseev_old, "покажите, на что способны!", bg.lab_mais)]

         ],
        # 1
        [[],
         [(moiseev_old, "Хорошо! Отлично! Проверка окончена. Сдавайте оборудование.", bg.lab_mais),
          (semen_old, "В смысле!? Нет!", bg.lab_mais),
          (kamil_old, "Естественно, что нет. На этом можно заработать немало!", bg.lab_mais),
          (semen_old, "все ясно с тобой, друг.", bg.lab_mais),
          (moiseev_old, "Похоже, что придется действовать по-плохому. Охрана!", bg.lab_mais)]
         ],
        # 2
        [[(None,
           ("Выбравшись через верхние этажи и спрыгнув вниз, ",
            "мы не получили травм благодаря регенерации о которой бормотал Моисеев."),
           bg.kazan_city_2050),
          (None,
           ("оглянувшись, мы увидели, как трое спортсменов бегут в здание DAUNCORP.",
            "Но вот это явно ненаша проблема."),
           bg.kazan_city_2050),
          (moiseev_old, "Эти дуралеи сбежали. Но мой план все еще в силе!", bg.lab_mais),
          (moiseev_old, "Хорошо, что я оставил в запасе еще Абобы ос для", bg.lab_mais),
          (artestro_old, "Там еще прибежали, говорят, что ищут беглецов.", bg.lab_mais),
          (moiseev_old, "впускай их сюда.", bg.lab_mais)
          ],
         [(pau, "А я ничешный такой)", bg.kazan_city_2050),
          (bt25, "Почему я похож на танк времен 2-ой мировой?", bg.kazan_city_2050),
          (pau, "Ты меня не спрашивай. Я без понятия, что курил этот Моисеев.", bg.kazan_city_2050),
          (bt25, "Я пошел сдавать эту «Абобу.»", bg.kazan_city_2050),
          (trio, "Рано радуетесь, воры.", bg.kazan_city_2050),
          (pau, "Когда они успели здесь оказаться?!", bg.kazan_city_2050),
          (bt25, "трюк с аркой больше не прокатит.", bg.kazan_city_2050)]
         ],
        # 3
        [[(trio, "Я вас задавлю!", bg.kazan_city_2050),
          (pau, "он не шутит!", bg.kazan_city_2050),
          (None, ("Эти 3-ое внезапно взяли и за долю секунды преодолели расстояние, ",
                  "чуть больше 1-ой мили!",
                  "Но, задеть героев, что странно им не удалось"), bg.kazan_city_2050),
          (bt25, "0_0", bg.kazan_city_2050),
          (None, "Пару часов спустя", bg.kazan_city_2050),
          (kamil_old, "Барахолка – самое бесполезное место в мире!", bg.kazan_city_2050),
          (semen_old, "Абобу снять просто так не получится...", bg.kazan_city_2050),
          (None, "Даун корп.", bg.daun_corp_2050),
          (moiseev_old, ("остался прототип в запасе... От недочета в нем я тоже избавился. ",
                         "Tеперь мне нужно найти того, кто поможет мне забрать Абобу Камиля и Семена.",
                         " У кого то из них именно та Абоба, которая подходит для создания реплик."), bg.lab_mais),
          (moiseev_old, ("Одна Важная личность уже согласилась на помощь.",
                         " Мне нет времени ждать троих подопытных.",
                         " Я сам пойду на их поиски."), bg.lab_mais),
          (None, "...", bg.black),
          (moiseev_old, "Кто-то здесь есть. Может она в силах мне помочь?", bg.adymnar_2050),
          (albina, "Привет", bg.adymnar_2050),
          (None, "Моисеев был так ошарашен, что не мог сказать и слова в ответ.", bg.adymnar_2050),
          (moiseev_old, "мм-мне нуж-жна помощь. У-украли... дам денег", bg.adymnar_2050),
          (albina, "вот деньги — это хорошо... давай, говори, что делать.", bg.adymnar_2050)],
         [(kamil_old, ("я не понимаю, как это работает, я хочу стать человеком, и ",
                       "я становлюсь. Как он это сделал?"), bg.kazan_city_2050),
          (semen_old, "Cразу видно откуда у него так много денег.", bg.kazan_city_2050),
          (kamil_old, "Ага. Сестра не дождалась", bg.kazan_city_2050),
          (pau, "Все?", bg.kazan_city_2050),
          (bt25, "Да, это конец.", bg.kazan_city_2050),
          (police, "Вы кто такие? ", bg.kazan_city_2050),
          (pau, "Мы просто тут стоим ", bg.kazan_city_2050),
          (police, "Неизвестный танк в городе и какой-то черный! Нейтрализовать!", bg.kazan_city_2050)]
         ],
        # 4
        [[(pau, "Похоже, что лучше скрыться... ", bg.kazan_city_2050),
          (pau, "Пока не поздно.", bg.kazan_city_2050),
          (albina, "Эй, а о чем вы там разговариваете?", bg.daun_corp_2050)],
         [(bt25, "ты кто?", bg.daun_corp_2050),
          (albina, ("Я - Альбинос! Просто отдайте мне Абобу ос, ",
                    "мы разойдемся, и я получу свои деньги."), bg.daun_corp_2050),
          (pau, "нет мы оставим Абобу себе.", bg.daun_corp_2050),
          (bt25, "тогда будем сражаться", bg.daun_corp_2050),
          (None, ("Альбина достала телефон из кармана и начала нас снимать.",
                  " Герои успели вовремя увернуться. ",
                  "Когда они обернулись, то увидели, что машина, ",
                  "которая стояла позади исчезла."), bg.daun_corp_2050)]
         ],
        # 5
        [[(moiseev_old, ("НЕТ!!!",
                         "Как вы не понимаете!?",
                         "Я делаю это на благо Государства! ",
                         "Если вы не отдадите Абобу, то всего этого может не стать!"),
           bg.daun_corp_2050),
          (bt25, "Что за чушь ты несешь!?", bg.daun_corp_2050),
          (moiseev_old, ("Похоже мне с вами говорить неочем...",
                         "Хорошо, что время я зря не терял."), bg.daun_corp_2050),
          (bulat, "Моисеев сказал, что даст Абобу если я справлюсь с вами.", bg.daun_corp_2050),
          (semen_old, "Булат!? – Как ты его ...", bg.daun_corp_2050),
          (moiseev_old, "Исхаков Индастрис было найти не так уж и просто.", bg.daun_corp_2050),
          (bulat, "Конечно, ты же забрал мой единственный филиал в Казани!", bg.daun_corp_2050),
          ],
         [(moiseev_old, "не будем разглагольствовать.", bg.daun_corp_2050),
          (
              None, "Метким нажатием кнопки Булат подорвал бое укладку Камилю и переключился на Семёна",
              bg.daun_corp_2050),
          (pau, "постой, мы же друзья!", bg.daun_corp_2050),
          (bulat, "Я не знаю кто ты.", bg.daun_corp_2050),
          ]
         ],
        # 6
        [[(semen_old, "постой!", bg.daun_corp_2050),
          ],
         [(bulat, ("Семён?! Этот болван меня вокруг пальца обвел, говорил, что вы террористы!",
                   "Скорее всего и про Америку он наврал...",
                   "Так или иначе он уже никак не откупится."), bg.daun_corp_2050),
          (moiseev_old, "Взять его!", bg.daun_corp_2050),
          ]
         ],
        # 7
        [[(moiseev_old, "Идиот! Ты не понимаешь, к чему твои действия приведут!", bg.daun_corp_2050),
          (bulat, "Мы уходим.", bg.daun_corp_2050),
          (semen_old, "Спасибо за помощь, Булат ", bg.daun_corp_2050),
          (bt25, "Да уж, спасибо.", bg.daun_corp_2050),
          ],
         [(None, "Через пару часов в DAUNCORP", bg.daun_corp_2050),
          (artestro_old, "вам действительно так нужна Абоба?", bg.lab_mais),
          (moiseev_old, "Без нее Государству не выстоять.", bg.lab_mais),
          (artestro_old, "Так у вас там еще одна лежит на столе.", bg.lab_mais),
          (moiseev_old, "Как? я же делал только на 3-оих для теста и на 3-оих для операции.", bg.lab_mais),
          (artestro_old, "Я добавил в пачку свою ", bg.lab_mais),
          (moiseev_old, ("Дай-ка взгляну...",
                         "Это она та самая для реплики! Похоже, что твоя,",
                         " со старым накопителем досталась одному из них."), bg.lab_mais),
          (artestro_old, "Это значит, что мы можем продолжить работу?", bg.lab_mais),
          (moiseev_old, "Да.", bg.lab_mais),
          (None, "Пару дней спустя...", bg.daun_corp_2050),
          (moiseev_old, "Сейчас...", bg.lab_mais),
          (moiseev_old, "...", bg.lab_mais),
          (moiseev_ten, "Времени нет. Это были необходимые меры.", bg.lab_mais),
          (None, "Mоисеев говорил с артистом по телефону ", bg.lab_mais),
          (artestro_old, "Скоро?", bg.lab_mais),
          (moiseev_ten, "Да. Альбина с тобой в Саратове?", bg.lab_mais),
          (artestro_old, "Естественно.", bg.lab_mais),
          (moiseev_ten, ("Хорошо. Я тоже скоро прибуду.",
                         "Передай ей, что я хочу сохранить ее"), bg.lab_mais),
          (None, "*Взрывы*", bg.destroyed_daun_corp),
          (pau, "Что это было!?", bg.destroyed_daun_corp),
          (bt25, "Ужас...", bg.destroyed_daun_corp),
          (bulat, ("похоже, что Моисеев был прав. Уже поздно.",
                   "Нам нужно его найти. Может у него есть запасной план?"), bg.destroyed_daun_corp),
          (bt25, "как ты выжил?", bg.destroyed_daun_corp),
          (bulat, ("Конечно, технология Моисеева на несколько степеней превзошла мои,",
                   "но у меня тоже есть пару тузов в рукаве)"), bg.destroyed_daun_corp),
          (pau, "Похоже здесь мы его не найдем", bg.destroyed_daun_corp),
          (negrominator, "Цель: Уничтожить.", bg.destroyed_daun_corp),
          (bt25, "Что это ", bg.destroyed_daun_corp),
          (bulat, "Это – то, о чем предупреждал Моисеев: ВС США.", bg.destroyed_daun_corp)
          ]
         ],
        # 8
        [[(negrominator, "Они используют прототип абоба ос 4", bg.destroyed_daun_corp),
          (negrominator, "Нам нужно больше огневой мощ...", bg.destroyed_daun_corp),
          (None, "От мощного выстрела, голова негроминатора превратилась в месиво", bg.destroyed_daun_corp)
          ],
         [(aks_mech, "Семен!", bg.destroyed_daun_corp),
          (None, "Негроминаторы увидев его, быстро разбежались кто куда.", bg.destroyed_daun_corp), ]
         ],
        # 9
        [[(pau, "Шевцов 47?!", bg.destroyed_daun_corp),
          (aks_mech, "Tы с кем-то меня спутал", bg.destroyed_daun_corp),
          (pau, "Как ты узнал?", bg.destroyed_daun_corp),
          (aks_mech, "*Он не помнит...*", bg.destroyed_daun_corp),
          (bt25, "ты же в Японии! Что ты здесь забыл?", bg.destroyed_daun_corp),
          (aks_mech, ("Япония – первая страна которой не стало... ",
                      "У них уже рука была набита. Ее не стало... ",
                      "Как и большей части мира где проживали белые."), bg.destroyed_daun_corp),
          (pau, "тогда что ты здесь делаешь?", bg.destroyed_daun_corp),
          (aks_mech, "спасаю свою шкуру", bg.destroyed_daun_corp),
          (bt25, "Эм, ну у нас тут ситуация не лучше", bg.destroyed_daun_corp),
          (aks_mech, "Здесь может и нет... Моя надежда – Саратов. Он еще работает?", bg.destroyed_daun_corp),
          (bulat, "Что работает?", bg.destroyed_daun_corp),
          (aks_mech, "Купол... Саратова...", bg.destroyed_daun_corp),
          (None, "5 минут назад...", bg.black),
          (artem_old, "Наконец нашлось время показать мой подвал)", bg.black),
          (egor, "Пипец, за все время ты так и не поменялся.", bg.black),
          (artem_old, "Что-то хлопнуло", bg.black),
          (egor, "похоже, наконец менты приехали за тобой!", bg.black),
          (artem_old, "Значит ливаем через запасной выход)", bg.black),
          (None, ("Артем и Егор вышли из подвала... и видят, как когда-то процветающий ",
                  "город превратился в руины."), bg.destroyed_daun_corp),
          (artem_old, "Ну судя по всему, ментов сегодня не будет.", bg.destroyed_daun_corp),
          (None, "Моисеев вышел из-за угла", bg.destroyed_daun_corp),
          (moiseev_ten, "Идёмте со мной, я вам помогу.", bg.destroyed_daun_corp),
          (artem_old, "И чем же ты поможешь?", bg.destroyed_daun_corp),
          (moiseev_ten, "Тагиру... Уже помог.", bg.destroyed_daun_corp)],
         [(None, "Саратов. ISKHAKOV INDUSTRIES", bg.saratov_iskhakov),
          (kamil_old, "Спасибо, что приютил нас, Булат.", bg.saratov_iskhakov),
          (bulat, "Это последнее мое место. Когда его покупал не знал, что оно может пригодиться", bg.saratov_iskhakov),
          (aksenov_old, "Купол Саратова даже спустя 28 лет работает отлично!", bg.saratov_iskhakov),
          (tagir_butterfly, "Да, Босс, я их вижу. Начинаю план капкан.", bg.saratov_iskhakov),
          (tagir_butterfly, "Начинаю атаку.", bg.saratov_iskhakov)]
         ],
        # 10
        [[(pau, "ОН УЛЕТАЕТ!", bg.saratov_iskhakov),
          (bulat, "Тагир??!", bg.saratov_iskhakov),
          (aks_mech, "ДОГНАТЬ ПОДОНКА!!!", bg.saratov_iskhakov),
          (None, ("Все побежали за Тагиром, как стадо БАРАНОВ.",
                  " Никто из них не знал, что это была часть его плана."), bg.saratov_iskhakov)],
         [(moiseev_ten, "Привет, подонки, как вам DAUNCORP 2.0?", bg.saratov_moiseev),
          (egor, "И почему я с Моисеевым?", bg.saratov_moiseev),
          (moiseev_ten, "Взять их! не дайте им помешать!", bg.saratov_moiseev)]
         ],
        # 11
        [[(None, ("Bсе практически перебили друг друга.",
                  " Егор, Даниил, Булат и Тагир – валялись все, кроме Камиля с Семеном.",
                  " Они стояли до последнего"), bg.saratov_moiseev),
          (moiseev_ten, "Эээ 2-е на одного! НЕЧЕСТНО!", bg.saratov_moiseev),
          (None, "Моисеев, как девочка, убежал прятаться в дом", bg.saratov_moiseev),
          (pau, "ДОГОНИМ ЕГО!", bg.saratov_moiseev),
          (bt25, "Может не надо? Это опять может оказаться ловушкой", bg.saratov_moiseev),
          (pau, "По-другому никак.", bg.saratov_moiseev),
          (None, ("Супер Пау сел на Камиля, и они на",
                  "всей скорости въехали в дом, опрокинув дверь,",
                  "За которой стояла..."), bg.saratov_moiseev),
          (moiseev_old, "Альбина!  НЕЕТ!", bg.black),
          (None, "Дверь упала на Альбину ", bg.black),
          (moiseev_ten, "Вы черти! Активировать АБОБА ОС 2!", bg.black),
          ],
         [(None, ("Из колбы под лестницей начало вылезать большая,",
                  "несокрушимая, напряженная масса, напоминавшая..."), bg.black),
          (pau, "ЛЕТАЮЩИЙ ЭЛЕКТРИЧЕСКИЙ ПЕЛЬМЕНЬ!", bg.saratov_moiseev),
          (None, "Камиль из-за нехватки ловкости быстро отлетел.", bg.saratov_moiseev)]
         ],
        # 12
        [[(None, ("Егор, очнувшись, решил добить гада и кинул в него Легендарный МЕШОК С обувью!",
                  "Пау увернулся от мешка и нажав L1+R1 отправил мешок в пельмень.",
                  "Не выдержав натиска мешка пельмень взорвался. Моисеев опять проиграл..."), bg.saratov_moiseev),
          (moiseev_ten, ("Я найду способ тебя починить, дорогая",
                         "Я найду, чего бы мне это не стоило"), bg.black),
          (None, "2 дня спустя", bg.black),
          (bulat, "Навигатор засек неизвестный источник энергии в районе Саратовского кинотеатра", bg.saratov_iskhakov),
          (pau, "Наверное, Моисеев никак не успокоится", bg.saratov_iskhakov),
          (bt25, "Ему так нужны наши АБОБЫ?", bg.saratov_iskhakov),
          (aks_mech, "Неважно, мы должны его остановить.", bg.saratov_iskhakov),
          (None, "Герои отправились в сторону Саратовского кинотеатра", bg.saratov_iskhakov),
          (aks_mech, "Что Это?", bg.saratov_cinema),
          (bt25, "Похоже на", bg.saratov_cinema),
          (pau, "Флэшку с надписью Абоба 3?", bg.saratov_cinema),
          (bt25, "Ты слепой? там написано 2050 -» 2023", bg.saratov_cinema),
          (pau, "Машина Времени", bg.saratov_cinema),
          (bulat, "Kогда он ее активирует, произойдет катастрофа", bg.saratov_cinema),
          (aks_mech, "эпицентр недалеко от нас...", bg.saratov_cinema),
          (bt25, "даже если краешком заденет...", bg.saratov_cinema),
          (pau, "Вперед! Нам нужно его остановить!", bg.saratov_cinema),
          (None, ("Кинотеатр был покинут.",
                  "Один шанс, чтобы остановить Моисеева.",
                  "Через пару минут герои были около бункера."), bg.saratov_cinema)
          ],
         [(bulat, "Похоже, тут никого нет.", bg.bunker),
          (pau, "Он где-то здесь, я его чувствую", bg.bunker),
          (bt25, "БЕРЕГИСЬ!", bg.bunker),
          (None, ("над головой Камиля пролетел мешок.",
                  "Из укрытия на героев напали слуги Моисеева!"), bg.bunker),
          (egor, "Ваша дорога окончится здесь!", bg.bunker),
          (artem_old, "Как вы меня бесите! Сапоги верните!", bg.bunker),
          (tagir_butterfly, "Где мой кэш?", bg.bunker),
          (None, "сражение будет эпичным.", bg.bunker),
          (aks_mech, "не дадим городу распасться", bg.bunker),
          (bulat, "вернём былое величие ISKHAKOV INDUSTRIES", bg.bunker),
          (bt25, "Добьёмся обещанных денег на ЛЕГО СФИНКС!", bg.bunker),
          (pau, "покончим с этим.", bg.bunker)]
         ],
        # 13
        [[(pau, ("Если я сейчас не найду Моисеева, то ",
                 "это может стать нашей конечной остановкой."), bg.bunker),
          (None, ("Воспользовавшись моментом, Пау проскочил ",
                  "сквозь недругов и попал в следующую комнату..."), bg.bunker),
          (pau, "МОИСЕЕВ!", bg.portal_albina),
          (moiseev_ten, "Ты опоздал! Этот портал рассчитан только на двоих!", bg.portal_albina),
          (pau, "Зачем ты это делаешь?", bg.portal_albina),
          (moiseev_ten, ("Чтобы стереть мои ошибки, как и вас!",
                         "Я больше не позволю вам притронутся к ней!"), bg.portal_albina),
          (moiseev_ten, "Моисеев начал двигаться в сторону портала. Альбина поползла за ним.", bg.portal_albina),
          (pau, "ТЕБЕ НЕ УЙТИ!", bg.portal_albina),
          (moiseev_ten, "Покойся с миром. Герой)", bg.portal_albina),
          (None, "Моисеев зашел в портал.", bg.portal_albina),
          (None, ("Пау, взлетая на паутине, стреляет в и так ползущую по",
                  "полу к порталу Альбину и..."), bg.portal_albina),
          (None, "…", bg.black),
          (None, "... Портал закрылся. Смертельная волна прошлась по всему Государству.", bg.black),
          (None, "Бункер был практически разрушен.", bg.black)],
         [(None, "2023 год. Школа Адымка.", bg.adymnar),
          (None, "Звонок", bg.adymnar),
          (tagir, "Эта старая рухлядь надоела меня спрашивать.", bg.adymnar),
          (kamil, "Хахахах ну лошара ты просто.", bg.adymnar),
          (semen, "Как и все мы. Мы единственный класс, который еще не закрыли на карантин.", bg.adymnar),
          (kamil, "Да, у нас больше половины класса нету. О чем они только дума...?", bg.adymnar),
          (None, "Bнезапный всплеск энергии прошелся по городу.", bg.blue),
          (semen, "Это что сейчас было?", bg.adymnar),
          (tagir, "Я лучше пойду", bg.adymnar),
          (aksenov, "Что это было? Чет у меня болит голова... пойду домой.", bg.adymnar),
          (kamil, "Из-за химии болит)", bg.adymnar),
          (artem, "Ты видел это?", bg.adymnar),
          (egor, "Чет странное.", bg.adymnar),
          (adel, "Это кто там балуется?", bg.adymnar),
          (aynur, "Без понятия.", bg.adymnar),
          (moiseev, "хм...", bg.adymnar),
          (None, "Тем временем в Казани... точное место неизвестно.", bg.kazan_city),
          (pau, "где я?", bg.kazan_city),
          (None, "Пау, только что пролетев через портал, оказался на улице.", bg.kazan_city),
          (pau, "Где Моисеев?!", bg.kazan_city),
          (None, ("Голубая волна уже как 2 раз исходила из странного места.",
                  "похоже оно было рядом с Пау."), bg.blue),
          (pau, "Это точно проделки Моисеева. Я иду за тобой, гад", bg.kazan_city),
          (None, "Tем временем Моисеев.", bg.moiseev_garage),
          (moiseev_ten, ("Если Альбина потеряется",
                         "Я найду ее с помощью этого изобретения и награжу ее",
                         "более совершенной Абобой. Зарядов точно хватит."), bg.angar),
          (pau, "Что ты опять задумал?", bg.angar),
          (moiseev_ten, ("ЧТО?! ДА КАК ТЫ?! НЕ МОЖЕТ БЫТЬ! ГДЕ АЛЬБИНА!",
                         "НЕ МЕШАЙ МНЕ! ТЫ ВСЁ ИСПОРТИШЬ!"), bg.angar),
          (None, "Пау ринулся на Моисеева и сломал его устройство управления.", bg.angar),
          (pau, "ТЫ УЖЕ ВСЕ ИСПОРТИЛ!", bg.angar),
          (moiseev_ten, "Гад!", bg.angar),
          (None, ("Пока два клоуна сражались, они затронули красные яркие",
                  "бочки с красивым восклицательным знаком в треугольнике."), bg.angar)]
         ],
        # 14
        [[(moiseev_ten, "ТЫ ВСЕ ИСПОРТИШЬ!", bg.angar_animated),
          (None, "Огонь распространился и до пункта управления. АБОБА ОС 4 ВЗЛЕТЕЛО!", bg.angar_animated),
          (moiseev_ten, "НЕЕТ!", bg.angar_animated),
          (pau, "Я УБЬЮ ТЕБЯ!", bg.angar_animated),
          (None, ("Огонь скоро дойдет до большой кучи красных бочек.",
                  "Моисеев, увидев это, достал свое свежее изобретение,",
                  "которое предназначено для извлечения АБОБЫ ОС. Он начал вытаскивать."), bg.angar_animated),
          (moiseev_ten, "УМРИ!", bg.angar_animated),
          (semen_old, "НЕТ!", bg.angar_animated),
          (None, "Взрыв.", bg.yellow),
          (None, "Здание было частично разрешено. Вокруг полыхающего огня столпились пожарные.", bg.black),
          (semen, "Фух! Химия закончилась, Меня не спросили", bg.adymnar),
          (artem, "Поздравляю...", bg.adymnar),
          (None, ("Сильный всплеск энергии.",
                  "Учеников школы Aдымка захватило."), bg.blue),
          (None, "Что!? Где я?", bg.loading_screen),
          (None, "Добро пожаловать в ABOBA OS 4.", bg.loading_screen),
          (None, "Какой АБОБА ОС?", bg.loading_screen),
          (None, "Пау, находясь в неизвестной колбе, разбил ее изнутри.", bg.loading_screen),
          (None, "Чего?", bg.loading_screen),
          (None, ("он был поражен, как легко это было сделатьТем временем,",
                  "из других колб начали выходить... Его одноклассники???"), bg.loading_screen),
          (dumpling, "О, я как раз хотел есть!", bg.loading_screen),
          (None, "Артём!?", bg.loading_screen),
          (bt25, "Наконец! Я докачался до батчата в риал лайф.", bg.loading_screen),
          (None, "Камиль?!", bg.loading_screen),
          (egor, "как раз хотелось вломить кому-нибудь мешком по голове.", bg.loading_screen),
          (None, "Егор.", bg.loading_screen),
          (None, "...", bg.black),
          (moiseev, "Эм... а где все?", bg.adymnar)
          ],
         [(None, "Пару дней спустя...", bg.black),
          (None, ("В НеонацУкр почти не осталось живой силы. Война истощила ее.",
                  "ВС Государства проводило масштабное наступление.",
                  "Западные страны боялись, что Государство на этом не остановится."), bg.black),
          (None, ("Егор с Артёмом сидели в Канализации и играли апех. Трое играли в мяч.",
                  "В это время к ним подошел Пау"), bg.canals),
          (pau, "Вы что там делаете?", bg.canals),
          (egor, "В апекс играем", bg.canals),
          (pau, "А почему в канализации?", bg.canals),
          (dumpling, "Мама не смогла принять, что я теперь пельмень", bg.canals),
          (egor, "Ты всегда им был.", bg.canals),
          (None, "Пока они болтали, они не заметили, как на них напали... Роботы?", bg.canals),
          (pau, "Это что за? Моисеев бот!?", bg.canals),
          (egor, "Ха-ха-ха, да, я согласен", bg.canals),
          (aynur, "Это что за железяка? А ну иди сюда!", bg.canals)]
         ],
        # 15
        [[(adel, "Что это за сила?", bg.canals),
          (None, "Пока все ржали, Моисеев боты схватили троих и быстро удалились.", bg.canals),
          (None, "взрывы.", bg.yellow),
          (pau, "Что происходит там?", bg.canals),
          (dumpling, "Без понятия. Если честно, то нам все равно.", bg.canals),
          (egor, "Апекс работает, больше не надо.", bg.canals),
          (None, "Пау поняв, что эти двое полностью отстали от жизни, вышел из канализации.", bg.canals)
          ],
         [(None, "Выстрел", bg.yellow),
          (None, "Выглянув на улицу, Пау увидел ужасную картину", bg.war_kazan),
          (pau, "Абрамсы!?", bg.war_kazan),
          (USAarmy, "Что это за клоунада!?", bg.war_kazan),
          (USAarmy, ("Не важно, стрелять во всех! Мы не можем ",
                     "допускать риски возможных наших потерь."), bg.war_kazan)
          ]
         ],
        # 16
        [[(None, ("Абрамс уже нацелился на Семёна,",
                  "который отбивался от морпехов."), bg.war_kazan),
          (None, "И вдруг, выстрел", bg.war_kazan),
          (bt25, "Помощь нужна?", bg.war_kazan),
          (pau, "Ты где был?", bg.war_kazan),
          (bt25, "Я игрался с сестрой в танчики, как вдруг!", bg.war_kazan),
          (bt25, "Теперь фронт здесь.", bg.war_kazan)
          ],
         [(USAarmy, "Не прекращать огонь!", bg.war_kazan)]
         ],
        # 17
        [[(president, "Нам нужно было действовать быстрее.", bg.kremlin),
          (minobr, "У нас больше нет другого выбора.", bg.kremlin),
          (minobr, ("Нам придется применить тактическую ядерную боеголовку.",
                    "Они нарушили наш суверенитет!"), bg.kremlin),
          (moiseev_ten, "НЕТ! Я могу предложить более выгодное решение без лишних жертв!", bg.kremlin),
          (president, "Что!? Кто это!? Как он здесь оказался? ", bg.kremlin),
          (moiseev_ten, ("Я могу обеспечить вас технологиями, которые будут превосходить",
                         "Американские на 25 - 30 ЛЕТ! Мне просто необходимо должное",
                         "финансирование. И часть армии."), bg.kremlin),
          (moiseev_ten, ("Вы не пожалеете, мы быстро освободим",
                         "оккупированные территории от Американцев."), bg.kremlin)
          ],
         [(artem, "Фух, все, я устал.", bg.canals),
          (egor, "Да ну, еще бы посидели поиграли пару деньков.", bg.canals),
          (artem, "Да Аксёнов в Траков хочет. Наверное уже заждался меня.", bg.canals),
          (egor, "Ну ладно, давай выйдем. Хорошо, что теперь меня гномом уже не назовут)", bg.canals),
          (artem, "Ну я бы поспорил.", bg.canals),
          (None, "...", bg.black),
          (artem, "Так вот что за взрывы были!", bg.kazan_afterwar),
          (kids, "Помогите! *хнык* воспитателей... Их нет больше *хнык*", bg.kazan_afterwar),
          (egor, "Какой ужас! Кто это произошло?", bg.kazan_afterwar),
          (kids, ("Дяди военные пришли *хнык* бормотали что-то",
                  "на непонятном *хнык* воспитатели пытались нас защитить... и.… и.…"), bg.kazan_afterwar),
          (artem, ("У меня дома есть подвал, там безопасно",
                   "и можно укрыться от взрывов. Пойдемте за мной"), bg.kazan_afterwar),
          (egor, "Артем! Недоумок! Меня на детей променял!", bg.kazan_afterwar),
          (moiseev_bot, "Цель обнаружена! Это Гном. Начинаю захват.", bg.kazan_afterwar),
          (egor, "Ты балбес!? Какой Гном!? Да я вам сейчас дам...", bg.kazan_afterwar)
          ]
         ],
        # 18
        [[(None, "Егор смог победить нескольких ботов, но количество их исчислялось десятками.", bg.kazan_afterwar),
          (None, "Его забрали...", bg.black),
          (USAarmy, "Нужно уходить!", bg.kazan_afterwar),
          (USAarmy, "Подожди, это их вооружение... Необходимо забрать это с собой", bg.kazan_afterwar),
          (None, "И к сегодняшним новостям.", bg.black),
          (None, ("Правительство подписало указ о размещении новой",
                  "военной техники на территории оккупированных Американскими войсками городов."), bg.black),
          (None, ("Защитные купола были размещены в центрах городов государственной важности.",
                  "Также сообщается о специальных военных роботах, помогавших прогнать ",
                  "Американцев из нашей страны... Американские силы начинают сдавать свои",
                  "позиции. Наши войска продавливают их вглубь Европы."), bg.black),
          (kamil, "Интересно, не те ли это роботы, которые нападали на Троицу?", bg.adymnar),
          (semen, ("Не, я так не думаю. Это ж были Моисеев боты.",
                   "А этот бот никогда бы не додумался сделать что-то ради своей страны."), bg.adymnar),
          (kamil, "Мне кажется наши способности, Моисеев боты, война... Это всё как то связано.", bg.adymnar),
          (gos_army, "ВЫ, ДВОЕ! СДАВАЙТЕСЬ ПО ХОРОШЕМУ!", bg.adymnar),
          (semen, "Что?", bg.adymnar),
          (kamil, "Государство пришло за нами! Я так и знал", bg.adymnar),
          (semen, "ПРЫГАЙ!", bg.adymnar),
          (kamil, "А, что?", bg.adymnar),
          (semen, "ПРЫГАЙ!!!", bg.adymnar),
          (None, ("Семен взлетел и подбросил Камиля в сторону окна. Рефлекторно они превратились ",
                  "в Bt25t и Супер Пау. Пау, падая, зацепился паутиной за здания, а Камиль нет."), bg.adymnar),
          (None, ("Он упал вниз головой и был парализован. Смотревшие на этот цирк вооружённые силы",
                  "Государства прострелили упавшему Камилю бензобак. Это позволило Моисеев ботам",
                  "беспрепятственно захватить Камиля увезти его."), bg.adymnar),
          (pau, "Я не могу это просто так оставить.", bg.adymnar)],
         [(pau, "Похоже, что его привезли сюда.", bg.moiseev_garage),
          (gos_army, "Он сам к нам пришел! Обезвредить его!", bg.moiseev_garage)]
         ],
        # 19
        [[(None, "Пау разобрался с последним Моисеев ботом.", bg.moiseev_garage),
          (None, "Удар сзади... Сэнс не спас.", bg.black),
          (semen, "Г-где я?", bg.angar2),
          (moiseev_ten, "Наконец, я верну её! Ты в моем подвале, дружок)", bg.angar2),
          (semen, "Я был в школе, а затем... я здесь?", bg.angar2),
          (moiseev_ten, ("Мне не хватало последнего Абобы ос чтобы запитать Ускоритель!",
                         "Я настолько гений, что могу сделать его в гараже 22го года!"), bg.angar2),
          (semen, "Я-я ничего не помню.", bg.angar2),
          (moiseev_ten, ("Похоже вся память с момента подключения записывалась на Абобу ос.",
                         "Я изучал это. Первый мой подопытный УМЕР от этого."), bg.angar2),
          (moiseev_ten, "ВСГ, можете избавиться от него.", bg.angar2),
          (gos_army, "Ну, скелет в шкафу нам не нужен, мы просто выбросим его на улицу.", bg.angar2),
          (moiseev_ten, "Да мне все равно, делайте с ним что хотите.", bg.angar2),
          (semen, "Что это было?", bg.moiseev_garage),
          (None, "Семена вышвырнули к обломкам, которые образовались после взрыва.", bg.moiseev_garage),
          (semen, ("Мне нужно сделать что-то. Камиль, Егор,",
                   "Артем и остальные были со мной. Они остались там."), bg.moiseev_garage),
          (None, "И тут Семён заметил что-то лежащее на полу, похожее на флэшку.", bg.moiseev_garage),
          (semen, "Я видел что-то подобное у Него в подвале. Он извлекал это из Артема. Но, она другая..."
                  "Oнa вставляется в…", bg.moiseev_garage),
          (None, "Всплеск воспоминаний", bg.loading_screen)
          ],
         [(None, "Он всё вспомнил. Но эти воспоминания были... не его", bg.moiseev_garage),
          (pau, "Моисеев... Что он натворил! Если я его не остановлю...", bg.moiseev_garage),
          (pau, "Что это?", bg.blue),
          (pau, "ПОРТАЛ! Все как тогда!", bg.moiseev_collider),
          (pau, "Сейчас он не уйдет!", bg.moiseev_collider),
          (moiseev_ten, "КАК!? Я... Я же забрал у тебя!", bg.moiseev_collider),
          (pau, "Что ты устроил, урод?", bg.moiseev_collider),
          (moiseev_ten, "СВАЛИ!", bg.moiseev_collider),
          (None, "Моисеев оттолкнул Пау.", bg.moiseev_collider),
          (None, "Портал в небе начал бушевать.", bg.moiseev_collider),
          (moiseev_ten, "ДАВАЙ, МОЯ ДОРОГАЯ! ИДИ СЮДА!", bg.moiseev_collider),
          (None, "Из неба начали падать... Булат...", bg.moiseev_collider),
          (pau, "Камиль?!", bg.moiseev_collider),
          (moiseev_ten, "ГДЕ, ГДЕ!? Альбина?!", bg.moiseev_collider),
          (bulat, "Семен!", bg.moiseev_collider),
          (bt25, "СЕМЕН!!!!", bg.moiseev_collider),
          (bulat, "Куда нас?", bg.moiseev_collider),
          (bt25, "Неужели... Не вышло... Мы проиграли...", bg.moiseev_collider),
          (moiseev_ten, "ЧТО! НЕТ, ГДЕ ЖЕ ОНА?!", bg.moiseev_collider),
          (bt25, "Её убил...", bg.moiseev_collider),
          (None, ("Моисеев, в ярости, использовал извлекатель Абобы ос на Камиле.",
                  "Камиль в свою очередь попытался выстрелить в Моисеева лазером,",
                  "чтобы его застанить. Но это не помогло."), bg.moiseev_collider),
          (kamil_old, "НЕЕТ!", bg.moiseev_collider),
          (None, "Его организм не выдержал, и он скончался.", bg.moiseev_collider),
          (bulat, "КАМИЛЬ!", bg.moiseev_collider),
          (pau, "Так и надо этому импостеру.", bg.moiseev_collider),
          (None, "Роботы Моисеева в это время не дремали и начали нападать", bg.moiseev_collider),
          (bulat, "Займись Моисеевым! Я задержу их!", bg.moiseev_collider)]
         ],
        # (, "", bg.),
        # 20
        [[],
         [(None, "Пока булат сражался с остатками роботов Моисеева, Моисеев...", bg.moiseev_collider_animated),
          (None, "...переключился на Пау.", bg.moiseev_collider_animated),
          (moiseev_ten, "ТЫ... ЭТО ВСЕ ИЗ-ЗА Тебя!", bg.moiseev_collider_animated),
          (pau, "Я хочу реванш.", bg.moiseev_collider_animated)]
         ],
        # 21
        [[(None, ("Моисеев потянулся извлекателем в направлении Пау.",
                  "Пау смог увернуться и применить извлекатель на Моисееве."), bg.moiseev_collider_animated),
          (moiseev_old, "Где я?", bg.moiseev_collider),
          (pau, "Ты побеждён.", bg.moiseev_collider),
          (moiseev_old, "Похоже вся память с момента подключения запи...", bg.moiseev_collider),
          (None, "Пау, не желая больше его слушать, раздавил голову Моисееву.", bg.moiseev_collider),
          (pau, "Пошёл ты.", bg.moiseev_collider),
          (bulat, "Так ему и надо.", bg.moiseev_collider),
          (pau, "Я потерял тех друзей, мне нужно спасти этих.", bg.moiseev_collider),
          (bulat, "Пошли.", bg.moiseev_collider),
          (None, "Пау зашел в гараж и нашел там Камиля, Егора, Артема и троицу", bg.angar2),
          (bulat, "Я отведу их в безопасное место.", bg.angar2),
          (pau, "Спасибо.", bg.angar2),
          (None, "Пау ушел.", bg.angar2),
          (bulat, ("Те роботы, с которыми я сражался, были очень похожи на...",
                   "Негроминаторов..."), bg.angar2),
          (None, "Булат посмотрел на выход из гаража.", bg.angar2),
          (bulat, "Пау уже ушёл.", bg.angar2),
          (None, "Булат мельком заметил Моисеева, который подглядывал за ним из-за двери.", bg.angar2),
          (moiseev, "...", bg.angar2),
          (None, "Увидев, что его заметили, Моисеев быстро спрятался за дверь и убежал.", bg.angar2),
          (bulat, ("ДА НУ!",
                   "Если это так... Я-я должен это остановить"), bg.angar2),
          (bulat, "Я закрою этот цикл.", bg.angar2),
          (None, "...", bg.black)],
         [(None, "Hесколько дней спустя. ", bg.adymnar),
          (tagir, "Где Турка? Он мне должен за обед!", bg.adymnar),
          (aksenov, "Возможно, что им в падлу приходить в школу.", bg.adymnar),
          (semen, "Ну не знаю. Уже достаточно времени прошло. Нужно с этим что-то сделать.", bg.adymnar),
          (aksenov, "Наверное.", bg.adymnar),
          (None, "После школы.", bg.kazan_city),
          (pau, ("Булат обещал, что он оставит всех в покое и вернет к нормальной жизни.",
                 "Надо связаться с ним. Можно позвонить кому-то"), bg.kazan_city),
          (None, "Семён позвонил Камилю.", bg.kazan_city),
          (question, "Да?", bg.kazan_city),
          (pau, "Камиль, Это Семён.", bg.kazan_city),
          (bulat_phone, "Это Булат. Что такое?", bg.kazan_city),
          (pau, "Где все?", bg.kazan_city),
          (bulat_phone, "Они в.… безопасном месте. Я позаботился о них.", bg.kazan_city),
          (pau, "Что ты задумал?!", bg.kazan_city),
          (bulat_phone, "Я сделаю этот мир лучше. В будущем.", bg.kazan_city),
          (pau, "Где ты? Оставь их в покое!", bg.kazan_city),
          (bulat_phone, "Твой маленький мозг не поймет всего масштаба происходящего", bg.kazan_city),
          (None, "Булат завершил вызов.", bg.kazan_city),
          (pau, "ТВАРЬ! Я ЕМУ ДОВЕРЯЛ! Что он с ними сделает?", bg.kazan_city),
          (None, "И тут Семён пораскинул мозгами.", bg.kazan_city),
          (pau, "ABOBA OS!", bg.kazan_city),
          (pau, "Когда Моисеев убил... предателя... она остались там!", bg.kazan_city),
          (None, "Пау прибыл на место недавней битвы.", bg.moiseev_garage),
          (pau, "ЧЕРТ! Он забрал Абобу!", bg.moiseev_garage),
          (None, "Пау снова позвонил Камилю", bg.moiseev_garage),
          (None, "Абонент недоступен, перезвоните позже.", bg.moiseev_garage),
          (pau, "Ну, позвоню тогда на Артёмин.", bg.moiseev_garage),
          (bulat_phone, "Да?", bg.moiseev_garage),
          (pau, "Пи..а! Что ты собираешься сделать с Абоба ОС?", bg.moiseev_garage),
          (bulat_phone, "Выпущу АБОБУ ОС НА СВЕТ РАНЬШЕ, ЧЕМ МОИСЕЕВ И ТОГДА! ЭТОМУ НЕ БЫВАТЬ!", bg.moiseev_garage),
          (pau, "И чему же?", bg.moiseev_garage),
          (bulat_phone, "Негроминаторам...", bg.moiseev_garage),
          (pau, ("ТЫ ТУПОЙ? Эксплуатация АБОБЫ ОС как раз и",
                 "привела к этим событиям! О чем ты говоришь?"), bg.moiseev_garage),
          (bulat_phone, "Как я уже говорил, твой маленький мозг не поймет.", bg.moiseev_garage),
          (pau, "Ты его блин изучал что-ли?", bg.moiseev_garage),
          (None, "Булат опять повесил трубку", bg.moiseev_garage),
          (pau, ("Мне необходимо его остановить! Если он будет использовать",
                 "Абобу ос, то это приведет к тому же исходу!"), bg.moiseev_garage),
          (pau, ("ПОГОДЬ! ГЕОЛОКАЦИЯ! У Артёма она всегда врублена!",
                 "Осталось понять, как отследить человека по ней."), bg.moiseev_garage),
          (None, ("Пау, после просмотра гайда быстро нашел место, где находится телефон Артёма.",
                  "Ядкс Карты завели его в метро."), bg.kazan_city),
          (pau, "Похоже это место. Я не вижу его. Опа! Телефон Артема! И Камиля! Я возьму.", bg.subway),
          (None, "Телефон Артёма внезапно включился.", bg.subway),
          (bulat_phone, "Зачем ты сюда пришел? Тебе не стоило этого делать.", bg.subway),
          (pau, "Где ты прячешь АБОБУ?", bg.subway),
          (bulat_phone, "А ты подумай)", bg.subway),
          (pau, "Сэнс звенит!", bg.subway),
          (bulat_phone, "Кек. Лол. Задержите его! ", bg.subway)]
         ],
        # 22
        [[(bulat_phone, "Сгори в Аду", bg.subway),
          (None, "Взрыв. Станция метро была полностью разрушена.", bg.yellow),
          (pau, "Что он творит! ОН СОВСЕМ С УМА СЪЕХАЛ? ЖИЗНИ ТОГО НЕ СТОЯТ!", bg.iskhakov_industries),
          (None, "Впервые в жизни Семёну не было на кого-то пофиг.", bg.iskhakov_industries),
          (pau, "Хм... Подумай... Ну где же может быть Булат?", bg.iskhakov_industries),
          (pau, "Булат... Исхаков... Исхаков Индастрис!", bg.iskhakov_industries),
          (None, "Здание стояло прямо перед Пау.", bg.iskhakov_industries),
          (pau, "Эта тварь далеко не ушла.", bg.iskhakov_industries),
          (None, "Семён зашел в здание. Внутри был администратор.", bg.iskhakov_industries),
          (artestro, "О, первый посетитель! Чем мы можем вам помочь?", bg.iskhakov_industries),
          (semen, "Мне нужно найти Булата.", bg.iskhakov_industries),
          (artestro, "-69 этаж.", bg.iskhakov_industries),
          (semen, "Спасибо!", bg.iskhakov_industries)
          ],
         [(None, "Семён поднялся вниз по лифту. Дверки открылись.", bg.black),
          (bulat, "Я же сказал, ужин только через час!", bg.bulat_lab),
          (pau, "Ах, хорошо, сейчас уйду!)", bg.bulat_lab),
          (bulat, ("Семен! Искать меня – грозить человечеству смертью!",
                   "Я делаю все для его дальнейшего существования!"), bg.bulat_lab),
          (pau, "Подрывая станцию метро?", bg.bulat_lab),
          (bulat, "Это лишь сопутствующий ущерб. Все для того, чтобы ты мне не мешал!", bg.bulat_lab),
          (pau, "Где АБОБА ОС?", bg.bulat_lab),
          (bulat, "Здесь...", bg.bulat_lab),
          (None, "Из-за тёмных углов выходят... Летающий пельмень, Трио, Егор повыше с мешком и.… bt-25 t",
           bg.bulat_lab),
          (pau, "Камиль! Я от тебя другого ожидать не мог! ", bg.bulat_lab),
          (dumpling, "Помогите моим детям!", bg.bulat_lab),
          (egor, "Не смей называть меня гномом!", bg.bulat_lab),
          (bt25, "Если из-за тебя мир рухнет... Я готов пойти на все... Ради премиум танков.", bg.bulat_lab),
          (pau, "Премиум танков...", bg.bulat_lab),
          (bulat, "Как видишь... друзья твои тебе не помогут!", bg.bulat_lab),
          (pau, ("Вы че, совсем с ума сошли? Это не Моисеев, вам незачем его слушаться!",
                 "Его слова - пустые обещания!"), bg.bulat_lab),
          (bulat, ("Как раз в точности, да наоборот! Когда Моисеев говорил,",
                   "но ничего не делал, я уже выделил на помощь детям Артема 100 РУБЛЕЙ!"), bg.bulat_lab),
          (trio, "Кончай с ним!", bg.bulat_lab)]
         ],
        # 23
        [[(None, ("Артем мощным разрядом откинул Пау в стену, разрушив ее.",
                  " Пау заметил что-то ему знакомое на столе."), bg.bulat_lab),
          (pau, ("АБОБА ОС! У него их осталось всего-то 2 штуки!",
                 "НЕ УСПЕЛ ПУСТИТЬ В МАССОВОЕ ПРОИЗВОДСТВО!)"), bg.bulat_lab),
          (bulat, ("Дурак! Зачем ты оттолкнул его туда! Я-то думал, что эти",
                   "теоремы – пустышки! Оказывается, что нет."), bg.bulat_lab),
          (dumpling, "Соре", bg.bulat_lab),
          (pau, "И это все твои запасы?)", bg.bulat_lab),
          (bulat, "Отдай их, СЕЙЧАС!", bg.bulat_lab),
          (pau, "Ну так забери их у своей прислуги)", bg.bulat_lab),
          (bulat, "Нет! Ты не понимаешь! Мне нужен извлекатель!", bg.bulat_lab),
          (None, ("Пока Булат продолжал разглагольствовать, Пау увернулся от",
                  "удара трио, пролетел над Егором и залез в шахту лифта."), bg.bulat_lab),
          (pau, "Пока, друг!", bg.bulat_lab),
          (bulat, "ВЕРНИСЬ!", bg.bulat_lab),
          (None, "Когда булат додумался послать за Пау своих пешек, след его уже простыл.", bg.bulat_lab),
          (pau, ("Один я с этими болванами не справлюсь. Мне нужна помощь.",
                 "Похоже, что мне придется воспользоваться своей добычей"), bg.iskhakov_industries),
          (None, "Школа Адымка", bg.adymnar),
          (aksenov, "0_0 Спайдермен?", bg.adymnar),
          (tagir, "Охрипнуть, как ты делаешь все эти трюки?", bg.adymnar),
          (semen, "Это я.", bg.adymnar),
          (aksenov, "Семен!?", bg.adymnar),
          (None, "Даниил достал телефон и начал снимать.", bg.adymnar),
          (pau, "Убери пожалуйста свой Сяоми.", bg.adymnar),
          (tagir, "Ты пришел, чтобы похвастаться способностями?", bg.adymnar),
          (pau, "Мне нужна ваша помощь. И у меня есть план.", bg.adymnar),
          (None, "Тем временем в штабе Булата.", bg.iskhakov_industries),
          (bulat, "Нам нужно захватить город.", bg.bulat_lab),
          (bt25, "Зачем?", bg.bulat_lab),
          (bulat, ("Чтобы остановить Негроминаторов нам надо сделать так, чтобы я был правителем",
                   "этой страны, и когда у меня будет достаточно войск, я отправлю их в Америку!"), bg.bulat_lab),
          (dumpling, "Ну допустим.", bg.bulat_lab),
          (trio, "И как ты собираешься это сделать?", bg.bulat_lab),
          (bulat, ("Сделаю ОГРОМНОГО РАЗРУШИТЕЛЬНОГО РОБОТА! А хотя...",
                  "Он у меня уже есть. *Походу я понял куда делось мое",
                  "разрушительное оружие в 22-м.*"), bg.bulat_lab),
          (bulat, ("Нет... Если я сделаю..., то это значит... НЕТ. МОЙ ПЛАН - ЛУЧШИЙ.",
                   "Просто предшественник допустил... оплошность."), bg.bulat_lab),
          (bt25, "Разве это не ГЕНОЦИД?", bg.bulat_lab),
          (bulat, ("Я покажу правительству НАШУ МОЩЬ! И тогда они сдадутся без лишних жертв.",
                   "Моисеев боты нас не остановят."), bg.bulat_lab),
          (bulat, "КОМПЬЮТЕР! КОД: 2285.", bg.bulat_lab),
          (bulat, "Что не сделаешь ради спасения человечества.", bg.bulat_lab)],
         [(pau, ("Давайте, как я говорил. Вы отвлекаете их. Я займусь Камилем.",
                 "У меня есть на это средство."), bg.adymnar),
          (None, "взрывы", bg.yellow),
          (tagir_butterfly, "Что Это?", bg.bulats_robot),
          (aks_mech, "ЭТО ГИГАНТСКИЙ РОБОТ!", bg.bulats_robot),
          (pau, "Похоже Булат уже начал свой план по терроризированию города.", bg.bulats_robot),
          (None, ("Тагир незаметно, как бабочка, пролетел над головами и",
                  "сбросил Камешек на Артёма, который упал на Бт25."), bg.bulats_robot),
          (None, "А аниме баба, в которой сидел Данил, выстрелила прямо в Трио", bg.bulats_robot),
          (bt25, "ЭЙ, ТАМ НАРУШИТЕЛИ!", bg.bulats_robot),
          (bulat, "МОЧИ ИХ! ОНИ НЕ ДОЛЖНЫ НАМ ПОМЕШАТЬ!", bg.bulats_robot)]
         ],
        # 24
        [[(None, ("Пока Данил и Тагир сражались, Пау незаметно",
                  "подлетел к Камилю и паутиной обездвижил его"), bg.bulats_robot),
          (bt25, "Зачем ты это делаешь? ОСТАНОВИСЬ!", bg.bulats_robot),
          (pau, "Я уничтожу АБОБУ ОС.", bg.bulats_robot),
          (bt25, "Что?", bg.bulats_robot),
          (pau, "Булат хочет избавиться от будущих событий, так?", bg.bulats_robot),
          (bt25, "Так.", bg.bulats_robot),
          (pau, "Все будущие события произошли из-за АБОБЫ ОС, так?", bg.bulats_robot),
          (bt25, "Ну, так Моисеев разработал ее.", bg.bulats_robot),
          (pau, ("Он их не разрабатывал. Если мы Уничтожим АБОБУ, то Моисееву",
                 "нечего будет нам предложить, когда мы навестим его."), bg.bulats_robot),
          (bt25, "...хм... Если это так, то я с вами.", bg.bulats_robot),
          (pau, "Спасибо, Камиль. И еще, в танках новый ивент.", bg.bulats_robot),
          (None, "Пау передает Камилю его телефон.", bg.bulats_robot),
          (bt25, "Где он был?", bg.bulats_robot),
          (pau, "В метро, которое подорвал Булат.", bg.bulats_robot),
          (bt25, "Спасибо, Друг!)", bg.bulats_robot),
          (pau, "Сможешь вывести из строя эту бандурину?", bg.bulats_robot),
          (bt25, "Я займусь этим. Ты пока помогай остальным.", bg.bulats_robot),
          (pau, "За дело.", bg.bulats_robot),
          (None, "Пау пришёл на подмогу своим напарникам. Но, они уже не сражались?", bg.bulats_robot),
          (bulat, "Что-то ты поздновато, Семён)", bg.bulats_robot),
          (tagir_butterfly, "Булат предложил мне тучу денег) Мне все равно, что будет дальше.", bg.bulats_robot),
          (aks_mech, ("Я не хочу терять свои способности! Это первый раз, когда в моей жизни",
                      "случилось что-то крутое!"), bg.bulats_robot),
          (bulat, "Переубедить их было легче, чем отнять у маленького ребёнка конфетку!", bg.bulats_robot),
          (dumpling, "Обижаешь!", bg.bulats_robot),
          (pau, "*Сэнс заработал, похоже, что это оно.*", bg.bulats_robot),
          (pau, "У меня для вас тоже есть сюрприз!", bg.bulats_robot),
          (None, "Взрыв", bg.yellow),
          (None, "Вокруг огонь...", bg.broken_robot),
          (bulat, "Эй, вы здесь?", bg.broken_robot),
          (tagir_butterfly, "Да, вроде всё в порядке.", bg.broken_robot),
          (trio, "Все целы.", bg.broken_robot),
          (None, "Враги быстро восстановили строй, даже после ТАКОГО взрыва.", bg.broken_robot),
          (egor, "Вон он лежит!", bg.broken_robot),
          (None, "Всё. Кажется, что это конец.", bg.broken_robot),
          (bulat, "Ну так прикончите его! Что стоите как болваны?", bg.broken_robot),
          (None, "Вот-Вот и Артём Сделает решающий выстрел для всей планеты.", bg.broken_robot),
          (bulat, "ДАВАЙ", bg.broken_robot),
          (None, "Выстрел.", bg.yellow)
          ],
         [(bt25, "Я смотрю, тебе нужна помощь)", bg.broken_robot),
          (pau, "Как раз вовремя. Спасибо.", bg.broken_robot),
          (bulat, "Невозможно!", bg.broken_robot),
          (bt25, "Ну что, надо завершить начатое)", bg.broken_robot),
          (bulat, "Почему медлим? В АТАКУ", bg.broken_robot)]
         ],
        # 25
        [[(None, "На поле осталось только 3 человека использующие ABOBA OS.", bg.broken_robot),
          (bulat, "Я НЕ МОГУ В ЭТО ПОВЕРИТЬ!", bg.broken_robot),
          (bt25, "Сей...", bg.broken_robot),
          (None, "Булат опять взорвал бое укладку Камилю выстрелом.", bg.broken_robot)],
         [(pau, "ЧМО! Еще пытаешься сопротивляться!", bg.broken_robot),
          (bulat, "Остались только мы с тобой)", bg.broken_robot),
          (pau, "У меня достаточно причин убить тебя.", bg.broken_robot),
          (bulat, "Потанцуем)", bg.broken_robot)]
         ],
        # (, "", bg.),
        # 26
        [[(pau, "Наконец я замочил его. Он уже сделал достаточно.", bg.broken_robot),
          (bt25, "Спасибо, что ты поступил так. Ему бы всё равно дали пожизненное.", bg.broken_robot),
          (pau, "Могу?", bg.broken_robot),
          (bt25, "Да.", bg.broken_robot),
          (None, "Камиль больше не является обладателем ABOBA OS", bg.broken_robot),
          (pau, ("Дело сделано. Столько людей пострадало. На Земле остался только 1",
                 "экземпляр, и всё, что мне осталось сделать, чтобы закончить эту эпопею,",
                 " так это..."), bg.broken_robot),
          (None, "...", bg.broken_robot),
          (None, "Пару дней спустя.", bg.black),
          (kamil, "Как я ненавижу Химию!", bg.adymnar),
          (semen, "Ты не один такой.", bg.adymnar),
          (tagir, "Ага, эти контрольные просто ужас", bg.adymnar),
          (egor, "Всё, я дописал.", bg.adymnar),
          (kamil, "О, Гномик вернулся)", bg.adymnar),
          (egor, "Я блин Карлик", bg.adymnar),
          (adel, "Классный мяч ты купил, теперь будем весь день баскет тренировать", bg.adymnar),
          (turov, "Мама денег дала)", bg.adymnar),
          (aynur, "Теперь нам есть что сказать, когда мы в следующий раз не придем на химию.", bg.adymnar),
          (artem, "что-то тут темно, видимо давно не...", bg.black),
          (kids, "Дядя, это ты? Мы тут уже много времени сидим. Нам холодно и хочется кушать.", bg.black),
          (artem, "Эм... Не помню, чтобы я заводил детей. Но позаботиться о них надо.", bg.black),
          (None, "...", bg.black),
          (moiseev, "Алё, это Президент? Наша сделка всё еще в силе?", bg.broken_robot),
          (moiseev, "Да? отлично! Мне бы, кроме денег, здание для создания лаборатории...", bg.broken_robot),
          (moiseev, ("Как раз закрылось отделение ISKHAKOV INDUSTRIES в Казани?",
                     "Вы меня выручаете господин президент..."), bg.broken_robot),
          (moiseev, "Да, Спасибо. До свидания. Вам тоже удачи.", bg.broken_robot),
          (moiseev, "Похоже я нашел то, что искал. Этим можно заняться!", bg.broken_robot),
          (moiseev, "Ну-ка что там написано?", bg.broken_robot),
          (None, '"ABOBA OS"', bg.black)
          ],
         [(aksenov, 'Где я?', bg.broken_robot), (aksenov, 'Что произошло?', bg.broken_robot),
          (aksenov, 'Где Булат?', bg.broken_robot), (aksenov, '... *Он* убил его?', bg.broken_robot),
          (aksenov, "Если это так, то мне нужно уходить отсюда.", bg.broken_robot),
          (aks_mech, "ВОТ ЧЁРТ, АРМИЯ ГОСУДАРСТВА!", bg.broken_robot)]],
        # 27
        [[(aksenov, 'Мне нужно убираться отсюда куда подальше.', bg.broken_robot),
          (aksenov, 'Я не могу позволить ему забрать абобу.', bg.broken_robot),
          (aksenov, "Я валю в Японию...", bg.broken_robot),
          (aksenov, "...Давно хотел там побывать...", bg.broken_robot),
          (None, "Казань", bg.iskhakov_industries), (None, "В лаборотирии исхаков индастриз", bg.lab_mais),
          (moiseev, "наконец, я смог скопировать Абобу ос", bg.lab_mais),
          (artestro, "блин, слушай, круто", bg.lab_mais),
          (artestro, " А что это?", bg.lab_mais),
          (moiseev, "Это то, что даже в уме представить сложно", bg.lab_mais),
          (artestro, "ну так что это?", bg.lab_mais),
          (moiseev, " это возможность человека стать тем,", bg.lab_mais),
          (moiseev, "кем он захочет, всего лишь об этом подумав!", bg.lab_mais),
          (moiseev, "только пока я не нашел подходящего бета тестера...", bg.lab_mais),
          (artestro, "a кто тебе нужен?", bg.lab_mais),
          (moiseev, "Тот, кто будет", bg.lab_mais), (moiseev, "сражаться", bg.lab_mais),
          (artestro, "это можно устроить!", bg.lab_mais),
          (artestro, "давай-ка зайдем в FemTok", bg.lab_mais),
          (artestro, "Вот! Деффка феменистка! ", bg.lab_mais),
          (artestro, "Обсуждает и осуждает Японскую по**оиндустрию!", bg.lab_mais),
          (artestro, "говорит так убедительно, что сама бы пошла...", bg.lab_mais),
          (artestro, " и поубивала там всех!", bg.lab_mais), (moiseev, "замечательно! ", bg.lab_mais),
          (moiseev, "Значит-с находим ее, вставляем абобу и отправляем", bg.lab_mais),
          (moiseev, "ее в Японию на деньги Государства!", bg.lab_mais),
          (None, "1 день спустя", bg.lab_mais),
          (lisa, 'И что мне делать?', bg.lab_mais),
          (moiseev, "Ты летишь в Японию!", bg.lab_mais),
          (lisa, "ВСМЫСЛЕ!?", bg.lab_mais),
          (moiseev, 'Ну извини,не мы же д0**0 8^^^^^5 про Японию', bg.lab_mais),
          (lisa, "но, но...", bg.lab_mais),
          (moiseev, "I missed the part where thats my problem", bg.lab_mais),
          (moiseev, "ты отправляешся в Японию.", bg.lab_mais)
          ],
         [(lisa, 'ну, я тут...', bg.shop),
          (lisa, "И что дальше?", bg.shop),
          (yakuji, "Эй, девочка!", bg.shop),
          (yakuji, 'Ты чего по улице с оружием ходишь?', bg.shop),
          (lisa, 'А ты кто?', bg.shop),
          (yakuji, 'Тебя не это должно волновать! Это наша территория', bg.shop),
          (yakuji, 'Если не собираешься ничего здесь покупать, то проваливай!', bg.shop),
          (lisa, 'Нахал!', bg.shop)
          ]],
        # 28
        [[(police, 'Эй, ты что с ним сделала?', bg.shop)],
         [(lisa, 'Он не следил за языком, вот я его и покалечила', bg.shop),
          (police, 'ты точно не отсюда. Пойдешь со мной.', bg.shop),
          (lisa, ' я никуда с тобой не пойду!', bg.shop)]],
        # 29
        [[(civil, 'Что она творит?', bg.shop),
          (lisa, 'Боже, вы тут все как один. Я должна что-то сделать с этим местом.', bg.shop),
          (lisa, ' ?', bg.shop),
          (lisa, ' !?', bg.shop),
          (None, 'Казань.', bg.daun_corp),
          (moiseev, 'Похоже, что наш объект превосходит по силе всех, кто встает на ее пути!', bg.lab_mais),
          (moiseev, 'это именно то, чего я пытался добиться!', bg.lab_mais),
          (artestro, ' Сэр, похоже, что у нее сейчас какие-то проблемы', bg.lab_mais),
          (moiseev, 'всмысле!?', bg.lab_mais)],
         [(lisa, 'моя голова', bg.aboba),
          (lisa, 'что происходит?', bg.aboba),
          (lisa, 'меня отравили ?', bg.aboba),
          (pau, 'кто ты?', bg.aboba),
          (lisa, '0_0', bg.aboba),
          (lisa, 'это я должна задать тебе этот вопрос', bg.aboba),
          (pau, 'где он?', bg.aboba),
          (lisa, 'кто?', bg.aboba),
          (pau, 'старый носитель. Что ты с ним сделала?', bg.aboba),
          (lisa, 'я не понимаю о чем ты...', bg.aboba),
          (pau, '...', bg.aboba)]],
        # 30
        [[(lisa, 'Охх... ', bg.shop),
          (lisa, 'Ну и урод!', bg.shop),
          (lisa, 'он похож на того черного незнакомца, которого показывали по TB', bg.shop),
          (lisa, 'чего только в то время не происходило...', bg.shop),
          (lisa, 'ладно, я его победила. Забыли о нем.', bg.shop),
          (lisa, 'сейчас нужно сконцентрироваться на этом жалком местечке', bg.shop),
          (artestro, 'П%0997! Что с ней происходило!?', bg.lab_mais),
          (moiseev, 'Ясно, похоже мне придется изучить абобу подробнее.', bg.lab_mais),
          (artestro, 'Я думал, что ты изучил aboba os с ног до головы!', bg.lab_mais),
          (moiseev, 'Ее строение слишком сложное, чтобы изучить, ', bg.lab_mais),
          (moiseev, 'даже с помощью техники этого клоуна!', bg.lab_mais),
          (moiseev, 'одна деталь может и не достигать нанометра!', bg.lab_mais),
          (moiseev, 'похоже, мне понядобятся 10-тилетия на доскональное изучение', bg.lab_mais)],
         [(None, "Тем временем в Америке происходили массовые протесты. ", bg.america_streets),
          (None, ("Люди были недовольны исходом войны с Государством и требуют",
                  "смены правительства и политического строя. "), bg.america_streets),
          (None, ("ВС США присутствовали на каждом митинге и разгоняли протестующих",
                  "газовыми бомбами и огнестрельным оружием. "), bg.america_streets),
          (None, ("Продолжаться так больше не могло. Американское правительство решило",
                  "пойти на уступку народу и передало власть корпорации DeTech. По сути",
                  "это только усугубило ситуацию для народа."), bg.america_streets),
          (None, ("Вместо полицейских на улицах стали появляться роботы, которые при",
                  "малейшем отклонении могли превратить человека в пепел.",
                  "О свободе слова можно даже и не упоминать."), bg.america_streets),
          (vasisa_normal, "Я хочу послушать новый трек, но до ЗП осталось еще несколько месяцев.", bg.america_streets),
          (vasisa_normal, "Конечно, есть возможность воспользоваться торрен...", bg.america_streets),
          (None, "Обнаружена несанкционированная деятельность.", bg.america_streets),
          (vasisa_normal, "НЕЕЕЕТ!!!", bg.america_streets),
          (None, "...", bg.america_streets),
          (None, "Япония...", bg.city_center),
          (lisa, 'И как, мне донести речь до этой жалкой страны? ', bg.city_center),
          (yakuji, 'это она! Она!', bg.city_center),
          (yakuji, 'знаешь, за свои поступки надо отвечать.', bg.city_center),
          (lisa, 'да откуда вас столько?', bg.city_center)]
         ],
        # 31
        [[(lisa, 'Вам всем тут надо головы поотрубать!', bg.city_center),
          (yakuji, 'нет, не надо!', bg.city_center),
          (yakuji, 'Что мы можем сделать для вас?', bg.city_center),
          (lisa, 'я хочу изменить этот поганый остров!', bg.city_center),
          (lisa, 'я хочу... Встать у власти!', bg.city_center),
          (yakuji, 'но это... ', bg.city_center),
          (yakuji, '...', bg.city_center),
          (yakuji, 'откуда вы? Я знаю, что вы не из Японии', bg.city_center),
          (yakuji, 'Глаза у вас... Прямые.', bg.city_center),
          (lisa, 'Я родом из Государства', bg.city_center),
          (yakuji, 'Боюсь что это невозможно, так как Япония', bg.city_center),
          (yakuji, ' - это колония Американцев.', bg.city_center),
          (yakuji, 'Вас быстро свергнут!', bg.city_center),
          (lisa, 'и не надейтесь!', bg.city_center),
          (lisa, 'вы видели, на что я способна? У них и шанса не будет.', bg.city_center),
          (lisa, 'у меня есть регенерационные способности и невероятная сила', bg.city_center),
          (yakuji, 'ну тут поспорить сложно. Ладно. На это потребуется время.', bg.city_center),
          (yakuji, 'Пошли с нами.', bg.city_center)],
         [(None, "...", bg.black),
          (vasisa, "Где... Я?", bg.corporation_lab),
          (vasisa, "Что со мной случилось?", bg.corporation_lab),
          (None, "Тело Васисы напоминало кибернетическое. Она была подсоединена к креслу.", bg.corporation_lab),
          (vasisa, "Нужно выбраться отсюда. ", bg.corporation_lab),
          (None, "Васиса без труда выбралась из оков. ", bg.corporation_lab),
          (vasisa, "Как мне удалось так легко это сделать?", bg.corporation_lab),
          (None, "В это время мимо камеры с Васисой проходили ученые", bg.corporation_lab),
          (stolberg_early, "Вот поэтому нам необходимо досконально изучить это устройство.", bg.corporation_lab),
          (scientist, "Друзья! Мы можем забыть о роботах! Тест с Киборгами прошел успешно!", bg.corporation_lab),
          (scientist, ("Нет необходимости производить модель человека, когда можно найти",
                       "живого человека и использовать устройство на нем!"), bg.corporation_lab),
          (stolberg_early, "Гений! Это будет дешевле в несколько раз! ", bg.corporation_lab),
          (scientist, ("Да, но похищать Американцев скоро станет невозможно.",
                       "Их здесь не бесконечность."), bg.corporation_lab),
          (stolberg_early, "Мы подумаем над этим.", bg.corporation_lab),
          (vasisa, "Эй, а кто это?", bg.corporation_lab),
          (None, "ВНИМАНИЕ ПРОПАЖА ПОДОПЫТНОГО. НАЙТИ. ЗАДЕРЖАТЬ. УСТРАНИТЬ. ", bg.corporation_lab)]],
        # 32
        [[
            (None, "Васисе удалось скрыться. ", bg.corporation_lab),
            (None, '...', bg.city_center)
        ],
            [(None, '28 лет спустя. Япония.', bg.city_center),
             (None, '...', bg.city_center),
             (civil, 'Нет Х###Ю!!! НЕТ П###О! СВЕРГНУТЬ ВЛАСТЬ!!!', bg.parlament),
             (police, 'Держимся вместе!', bg.parlament),
             (lisa, 'вы нас не остановите, Беркутцы!', bg.parlament)]],
        # 33
        [[(yakuji, 'Итак, мы у парламента.', bg.parlament),
          (lisa, 'штурмуем их.', bg.parlament),
          (None, 'Казань, даун корпорейшн', bg.lab_mais),
          (artestro_old, 'Сэр, похоже, что наш подопотный начинает ', bg.lab_mais),
          (artestro_old, 'собирать группу революционеров за собой!', bg.lab_mais),
          (moiseev_old, 'всмысле!?', bg.lab_mais),
          (artestro_old, 'в прямом!', bg.lab_mais),
          (moiseev_old, 'надо срочно это прекратить! Нельзя позволить ей захватить там власть!', bg.lab_mais),
          (artestro_old, 'но, почему?', bg.lab_mais),
          (moiseev_old, 'Это колония Американцев! Kогда они увидят, что там творится', bg.lab_mais),
          (moiseev_old, ' ответный удар должен последовать незамедлительно!', bg.lab_mais),
          (artestro_old, ' почему вы так переживаете за эту страну?', bg.lab_mais),
          (moiseev_old, 'увидев, кто встал у власти, они будут считать ', bg.lab_mais),
          (moiseev_old, 'что Государство отвоевывает у них колонии!', bg.lab_mais),
          (moiseev_old, 'Я уже практически доработал Абобу...', bg.lab_mais),
          (moiseev_old, 'И скоро мне нужно будет искать новых бетатестеров', bg.lab_mais),
          (moiseev_old, 'для разведки ситуации в Америке', bg.lab_mais),
          (moiseev_old, 'но остановить этот беспредел надо сейчас.', bg.lab_mais),
          (moiseev_old, 'я даю тебе незавершенный абоба ос, дабы ты положил конец этому безобразию.', bg.lab_mais),
          (moiseev_old, 'ты отправляешься в Японию сейчас.', bg.lab_mais)],
         [(None, 'И снова Япония.', bg.parlament),
          (lisa, 'Наконец. Я у власти', bg.buildings),
          (yakuji, 'да, теперь осталось надеяться, что ответной реакции не поступит.', bg.buildings),
          (aksenov_old, 'Пипец их много!', bg.parlament),
          (aksenov_old, 'я не могу позволить, чтобы мой магазин закрыли!', bg.parlament),
          (aks_mech, 'нужно попытаться что то сделать.', bg.parlament)]],
        # 34
        [[(aks_mech, 'Это бесполезно. Их слишком много.', bg.parlament),
          (lisa, 'Какие тут просторы!', bg.buildings),
          (lisa, 'теперь вся страна моя!', bg.buildings),
          (lisa, 'больше не будет никаких женских притеснений!', bg.buildings),
          (lisa, 'Bозраст согласия мы поднимем до 30лет!', bg.buildings)],
         [(artestro_old, 'Tы не ведаешь, что творишь...', bg.buildings),
          (artestro_old, 'мне нужно тебя остановить пока не поздно.', bg.buildings),
          (lisa, 'еще один! Я вас как орешки щелкаю!', bg.buildings),
          (artestro_old, 'и не надейся', bg.buildings)]],
        # 35
        [[(lisa, 'А теперь -', bg.buildings),
          (lisa, 'проваливай!', bg.buildings),
          (None, 'Опять в Казани, спустя время.', bg.lab_mais),
          (artestro_old, 'извините...', bg.lab_mais),
          (moiseev_old, 'это еще не конец.', bg.lab_mais),
          (moiseev_old, 'американцы уже 20 лет скрывались, не подавая и шороху. ', bg.lab_mais),
          (moiseev_old, 'кто знает, какой ответный удар последует...', bg.lab_mais),
          (moiseev_old, 'Слушай. ', bg.lab_mais),
          (moiseev_old, 'Я только что доделал абобу ос.', bg.lab_mais),
          (moiseev_old, ' Проблема была в модуле памяти', bg.lab_mais),
          (moiseev_old, 'Сейчас я очистил его полностью.', bg.lab_mais),
          (artestro_old, 'это значит, что он готов?', bg.lab_mais),
          (moiseev_old, 'Возможно.', bg.lab_mais),
          (moiseev_old, ' Свою абобу можешь оставить себе, если хочешь.', bg.lab_mais),
          (moiseev_old, 'мне нужно, чтобы ты поискал мне новых бета тестеров', bg.lab_mais),
          (moiseev_old, 'они помогут мне узнать, хорошо ли новая абоба взаимодействует с человеком', bg.lab_mais),
          (moiseev_old, 'работают ли функции регенерации, может ли носитель стать тем, кем захочет и т.д.',
           bg.lab_mais),
          (artestro_old, 'хорошо, я сей...', bg.lab_mais),
          (moiseev_old, 'Иди мой полы! Ты облажался.', bg.lab_mais),
          (artestro_old, 'Ладно...', bg.lab_mais),
          (moiseev_old, 'После этих тестеров, мне понадобятся уже другие люди,', bg.lab_mais),
          (moiseev_old, ' которые и побегут в Aмерику.', bg.lab_mais),
          (moiseev_old, "предоставлю им невероятную скорость", bg.lab_mais),
          (artestro_old, '*Босс, подопотные бомжы нашлись быстро.*', bg.lab_mais)],
         [(None, 'Япония. Неделю спустя', bg.shop),
          (soldier, 'эй, ты что, не слышал? Все магазины, вроде твоего, закрываются.', bg.shop),
          (aks_mech, 'меня это не волнует. Тихий омут будет существовать вечно.', bg.shop),
          (soldier, 'значит, с этим местечком мы разберемся по-грязному.', bg.shop)]],
        # 36
        [[(aks_mech, 'и не пытайтесь. Это МОЙ магазин.', bg.shop),
          (lisa, 'Мне кажется, что истребл*ть моих людей было не лучшим твоим решением.', bg.shop),
          (aks_mech, 'это ты...', bg.shop),
          (aks_mech, 'зачем ты это делаешь?', bg.shop),
          (lisa, 'А вот это уже явно не твоя проблема.', bg.shop),
          (aks_mech, 'Как раз таки моя.', bg.shop),
          (lisa, 'Это уже неважно, ты отправишься на тот свет.', bg.shop),
          (lisa, ' ...', bg.shop),
          (aks_mech, '?', bg.shop),
          (lisa, 'ох...', bg.shop),
          (aks_mech, 'что с тобой?', bg.shop)],
         [(lisa, '...', bg.aboba),
          (pau, 'Я уничтожу тебя!', bg.aboba),
          (lisa, 'Нет! Только не сейчас!', bg.aboba)]],
        # 37
        [[(aks_mech, 'Она ослаблена! Мне нужно атаковать, пока есть возможность!', bg.shop)],
         [(lisa, 'Ой...', bg.shop)]],
        # 38
        [[(aksenov_old, 'Наконец с ней покончено.', bg.shop),
          (aksenov_old, 'Но такие ублюдки все еще ходят по городу.', bg.shop),
          (aksenov_old, 'мне необходимо с этим что-то дел...', bg.shop),
          (None, '*взрывы*', bg.yellow)],
         [(negrominator, 'УНИЧТОЖИТЬ ВСЕХ НЕДРУЖЕСТВЕННЫХ ОСОБЕЙ!', bg.city_ruins),
          (aks_mech, 'Что происходит?', bg.city_ruins)]],
        # 39
        [[(aks_mech, ' Их слишком много. Мне по-хорошему бы ливать.', bg.city_ruins),
          (artestro_old, 'Босс, американцы все-таки напали на Японию.', bg.lab_mais),
          (artestro_old, 'скоро там и мокрого места не останется', bg.lab_mais),
          (artestro_old, 'откуда у них такие технологии?', bg.lab_mais),
          (artestro_old, 'как будто у них был...', bg.lab_mais),
          (moiseev_old, 'Абоба ос. Слушай, мне надо тебе кое в чем признаться.', bg.lab_mais),
          (moiseev_old, 'помнишь то, как я защитил Государство в обмен на ', bg.lab_mais),
          (moiseev_old, 'эту лабораторию и финансирование?', bg.lab_mais),
          (artestro_old, 'это трудно забыть...', bg.lab_mais),
          (moiseev_old, 'это был не я.', bg.lab_mais),
          (artestro_old, 'как не вы?', bg.lab_mais),
          (moiseev_old, 'Как ты думаешь, откуда взялся абоба ос? ', bg.lab_mais),
          (moiseev_old, 'Тот, кто отразил атаку был моим... ', bg.lab_mais),
          (moiseev_old, 'клоном из будущего.', bg.lab_mais),
          (moiseev_old, 'похоже, во время 2022-го, американцам попала в руки абоба', bg.lab_mais),
          (moiseev_old, ' моего клона или кого-то еще', bg.lab_mais),
          (moiseev_old, 'им удалось воссоздать ее быстрее...', bg.lab_mais),
          (moiseev_old, 'за счет защитных куполов Американцам удавалось подавлять все,', bg.lab_mais),
          (moiseev_old, 'что приходило из вне в течение 20 лет!', bg.lab_mais),
          (moiseev_old, 'они создали армию на основе абобы.', bg.lab_mais),
          (moiseev_old, 'И сейчас, Генерал Армии уничтожает все живое, что осталось на', bg.lab_mais),
          (moiseev_old, 'бывшем острове п№3%:!индустрии.', bg.lab_mais),
          (artestro_old, 'ну до нас это надеюсь не дойдет?', bg.lab_mais),
          (moiseev_old, 'Дойдет... Я отправил мать в Саратов и мое новое изобретение -', bg.lab_mais),
          (moiseev_old, 'Абобу ос 2.0.', bg.lab_mais),
          (moiseev_old, 'Скоро и мы туда поедем.', bg.lab_mais),
          (artestro_old, 'А моя мать?', bg.lab_mais),
          (moiseev_old, 'ну тут сори, она закосплеит твоего отца)', bg.lab_mais)],
         [(aksenov_old, 'Итак, я в убежище', bg.shelter),
          (soldier, 'Эй! Это он убивал наших вместе с копами!', bg.shelter),
          (aks_mech, 'да блин!', bg.shelter)]],
        # 40
        [[(aks_mech, 'Прекратите!', bg.shelter),
          (aks_mech, 'Слушайте, я как она! Я могу их остановить!', bg.shelter),
          (aks_mech, 'В такой ситуации нам лучше объедениться.', bg.shelter),
          (police, 'Он правду говорит! Без него нам остаётся только гнить', bg.shelter)],
         [(soldier, 'Хорошо. Мы проверим, на что ты способен', bg.shelter)]],
        # 41
        [[(police, 'Здесь больше нет смысла оставаться.', bg.shelter),
          (soldier, 'Нам нужно отразить их удар и победить Генерала!', bg.shelter),
          (aks_mech, 'Генерала?', bg.shelter),
          (yakuji, 'Да. Это их предводитель. Мы мало чего о нем знаем. ', bg.shelter),
          (soldier, 'Известно одно, что он самый опасный тип из всех.', bg.city_ruins),
          (police, 'Но с тобой, я предпологаю, Генерал Армии нам нипочём.', bg.city_ruins),
          (aks_mech, 'Я уж надея...', bg.city_ruins),
          (None, '', bg.explosion),
          (aks_mech, 'Ох боже....', bg.city_ruins),
          (general, ')', bg.city_ruins),
          (general, 'Вы на что-то надеялись?', bg.city_ruins),
          (general, 'Это - за нападение на пентагон.', bg.city_ruins),
          (aks_mech, 'кхкх. Пентагон? ', bg.city_ruins),
          (general, 'Да. Я знаю, что это были одни из ваших.', bg.city_ruins)],
         [(aks_mech, 'Их здесь все больше и больше!', bg.city_ruins)]],
        # 42
        [[(general, 'Ничтожество!', bg.city_ruins),
          (None, 'Генерал Армии взял Меху Аксенова за шиворот ', bg.city_ruins),
          (None, 'И запульнул его в соседнюю многоэтажку.', bg.city_ruins)],
         [(aks_mech, 'У него тоже абоба?', bg.explosion),
          (general, 'Я тебя в пыль сотру.', bg.explosion),
          (aks_mech, 'Это мы посмотрим...', bg.explosion)]],
        # 43
        [[(aks_mech, 'Просто, знаешь... Василиса - это всего лишь тонировка... Когда встречусь с Моисеевым)',
           bg.explosion),
          (general, 'НЕЕЕЕТ!', bg.explosion),
          (aks_mech, 'Вот с ним и покончено..', bg.explosion),
          (aks_mech, 'Но страна уничтожена... и мой магазинчик тоже...', bg.explosion),
          (aks_mech, 'Остался только пепел', bg.explosion),
          (aks_mech, 'А что это?', bg.explosion),
          (None, '*ВНИМАНИЕ ВСЕМ ОТРЯДАМ*', bg.explosion),
          (None, '*МЫ НЕСЕМ МНОГОЧИСЛЕННЫЕ ПОТЕРИ*', bg.explosion),
          (None, '*МЫ ТРЕБУЕМ ПОДКРЕПЛЕНИЕ!*', bg.explosion),
          (aks_mech, 'Вы где?', bg.explosion),
          (None, '*ОКОЛО КАЗАНИ... ИЛИ ТОГО, ЧТО ОТ НЕЕ ОСТАЛОСЬ, БУДЬТЕ ГОТОВЫ', bg.explosion),
          (None, 'СТОЛКНУТЬСЯ С НИМИ*', bg.explosion),
          (aks_mech, 'С кем?', bg.explosion),
          (None, ' ТОЛЬКО НЕ СМЕЙТЕСЬ!*', bg.explosion),
          (None, '*СПАЙДЕРМЭН, КАКОЙ ТО ТАНК, И УЧЕНЫЙ-ШКАФ.*', bg.explosion),
          (aks_mech, 'А вот это не смешно.', bg.explosion),
          (aks_mech, 'похоже, что Симен все-таки взялся за старое...', bg.explosion),
          (aks_mech, 'НО! Он не хочет отбирать абобу.', bg.explosion),
          (aks_mech, 'Это мой шанс.', bg.explosion),
          (aks_mech, 'Я спешу к ним на помощь.', bg.explosion),
          (None, '...', bg.explosion)],
         []],
        # 44
        [[(aks_mech, ("Хорошо, что под рукой попался транспортник Американцев.",
                      "Так бы я за короткий срок не долетел."), bg.destroyed_daun_corp),
          (negrominator, "Они используют прототип Абоба ос 4", bg.destroyed_daun_corp),
          (negrominator, "Нам нужно больше огневой мощи...", bg.destroyed_daun_corp),
          (aks_mech, "Семен!", bg.destroyed_daun_corp)],
         []
         ],
        # 45
        [[(None, "Все начало повторяться вновь.", bg.destroyed_daun_corp),
          (pau, "МОИСЕЕВ!", bg.portal_albina),
          (moiseev_ten, "Ты опоздал! Этот портал рассчитан только на двоих!", bg.portal_albina),
          (pau, "Зачем ты это делаешь?", bg.portal_albina),
          (moiseev_ten, "Чтобы стереть мои ошибки, как и вас!", bg.portal_albina),
          (moiseev_ten, "Я больше не позволю вам притронуться к ней!", bg.portal_albina),
          (None, "Моисеев начал двигаться в сторону портала. Альбина поползла за ним.", bg.portal_albina),
          (None, " ... Бункер ... ", bg.bunker),
          (dumpling, ("Хватит сражаться! Если мы не покинем это место в",
                      "ближайшее время, то это мы взлетим на воздух вместе с этим местом "), bg.bunker),
          (aks_mech, "Вам тоже это известно? ", bg.bunker),
          (egor, "Да, Моисеев предупредил нас об этом.", bg.bunker),
          (bt25, "Уходим, Быстрее! ", bg.bunker),
          (tagir_butterfly, "А где Булат? Он только что был здесь.", bg.bunker),
          (None, "Смертельная волна энергии Абобы прошлась по всему Государству.  ", bg.bunker),
          (None, "Бункер был практически разрушен.", bg.bunker),
          (None, "Опять... ", bg.bunker)
          ],
         [(None, "Защитный купол был уничтожен вместе со взрывом.", bg.destroyed_iskhakov),
          (None, "Негроминаторы полезли из всех щелей. ", bg.destroyed_iskhakov),
          (aks_mech, "НЕТ!", bg.destroyed_iskhakov)]
         ],
        # 46
        [[(None, "Негроминаторов становилось все больше и больше", bg.destroyed_iskhakov),
          (None, ("После продолжительной битвы удалось скрыться только Егору",
                  "с Артемом. Остальных захватили Негроминаторы. "), bg.destroyed_iskhakov),
          (negrominator, "Похоже, что они не являлись войсками ВС Г. ", bg.destroyed_iskhakov),
          (general, "Интересно... Можно взять их изучение.", bg.destroyed_iskhakov),
          (egor, "Где Булат, когда он так нужен? ", bg.destroyed_iskhakov),
          (dumpling, "Не знаю. Спасать своих надо. Сядем на следующий транспортник.", bg.destroyed_iskhakov),
          (negrominator, "Похоже наши двигатели частично отказывают.  ", bg.destroyed_iskhakov),
          (general, "Запрос принят. Летим на базу. ", bg.destroyed_iskhakov),
          (None, "Америка.", bg.america_rooftops),
          (vasisa, "Похоже я опять в этом месте.", bg.corporation_lab),
          (vasisa, "Судьба водит меня сюда снова и снова", bg.corporation_lab),
          (vasisa, ("По некоторым источникам именно здесь хранится их новая",
                    "разработка - модуль невидимости "), bg.corporation_lab),
          (stolberg, ("Великолепная идея - поработить Африканские страны. Людей там так много,",
                      "что можно и не переживать о том. Что нас когда-либо свергнут. Особенно после",
                      "уничтожения Государства! Теперь останется только Китай."), bg.corporation_lab),
          (vasisa, "Опять он! Если получится пройти незаметно, то … ", bg.corporation_lab)
          ],
         [(None, "ВНИМАНИЕ! НЕЗАКОННОЕ ПРОНИКНОВЕНИЕ. ЦЕЛЬ - УНИЧТОЖИТЬ. ", bg.corporation_lab),
          (stolberg, "Опять ты...", bg.corporation_lab)]
         ],
        # 47
        [[(vasisa, "Это было непросто!", bg.corporation_lab),
          (vasisa, "Я нашла его!", bg.corporation_lab),
          (stolberg, "УНИЧТОЖИТЬ! ", bg.corporation_lab),
          (vasisa, "Еще роботы!", bg.corporation_lab)
          ],
         [(None, "Пока Васиса сражалась, она нагинатой задела пульт управления ", bg.corporation_lab),
          (trio, "Мы свободны!", bg.corporation_lab)]
         ],
        # 48
        [[(None, "После победы над ботами Троица тут же убежала, оставив Васису. ", bg.corporation_lab),
          (stolberg, ("Вам все равно не остановить нас. Судьба уже решилась.",
                      "Мы исключим вас из прошлого!"), bg.corporation_lab),
          (vasisa, "О чем он говорит?", bg.corporation_lab),
          (None, "Количество роботов все увеличивалось и увеличивалось.", bg.corporation_lab),
          (vasisa, "Похоже мне тоже пора убираться. ", bg.corporation_lab)
          ],
         [(None, "Пару часов спустя. ", bg.black),
          (negrominator, "Как вы думаете, они не проснутся?", bg.black),
          (general, "Не должны. Мы их так размотали, что никто бы уже не встал. ", bg.black),
          (None, "Транспортник приземлился.", bg.black),
          (negrominator, "Что ж пора их доставать.", bg.black),
          (tagir_butterfly, "Не тут-то было!", bg.america_rooftops)]
         ],
        # 49
        [[(bt25, "Уходим отсюда!", bg.america_rooftops),
          (tagir_butterfly, "Смотри, это здание!", bg.america_rooftops),
          (aks_mech, "похоже на то, что мы видели в кинотеатре.", bg.america_rooftops),
          (bt25, "Это не к добру. Пойдем туда.", bg.america_rooftops)],
         [(None, "В то же время... Где-то в Африке.", bg.black),
          (artem_old, "Что это за место?", bg.africa_conveyer),
          (artem_old, "Похоже, что тут производят негроминаторов из обычных людей.", bg.africa_conveyer),
          (artem_old, ("Если мы не отключим конвейер вовремя, то нас могут засечь.",
                       "Будет очень плохо."), bg.africa_conveyer),
          (egor, "Пока ты болтал, я взломал одного из шагоходов.", bg.africa_conveyer),
          (dumpling, "Значит устроим здесь мясорубку)", bg.africa_conveyer)
          ]
         ],
        # 50
        [[(dumpling, "Конвейер отключен!", bg.broken_conveyer),
          (egor, "Походу все негроминаторы начали агриться на нас!", bg.broken_conveyer)],
         []
         ],
        # 51
        [[(egor, "Нет! Их слишком много! Похоже, это конец!", bg.broken_conveyer),
          (dumpling, "Главное, что мы сделали благое дело. ", bg.broken_conveyer)],
         [(bt25, "Мы внутри.", bg.american_collider),
          (aks_mech, "Похоже на ускоритель для машины времени. ", bg.american_collider),
          (bt25, "Они хотят отправиться в прошлое?", bg.american_collider),
          (tagir, "Капец их тут!", bg.american_collider),
          (None, "Вдруг в здание ворвались трое бегунков.", bg.american_collider),
          (trio, "Мы без драки не останемся)", bg.american_collider),
          (aks_mech, "Держимся вместе!", bg.american_collider)
          ]
         ],
        # 52
        [[(None, "Пока все сражались кто незаметно пробежал мимо.", bg.american_collider),
          (vasisa, ("Хорошо, что я не одна, кто борется против DeTech.",
                    "Они задержат ботов пока я буду разбираться с Столбергом."), bg.american_collider),
          (None, ("Васиса добралась до крыши. Перед ней был энергетический шар,",
                  "похожий на сферу Дайсона."), bg.collider_top_1),
          (vasisa, "Что ты задумал?", bg.collider_top_1),
          (stolberg, "Нет! Как ты здесь оказалась?", bg.collider_top_1),
          (vasisa, "Еще раз задаю вопрос. От ответа будет зависеть твоя жизнь.", bg.collider_top_1),
          (stolberg, "Хорошо. Если ты хочешь знать правду, то вот:", bg.collider_top_1),
          (stolberg, ("Наша планета страдала во все времена. Добыча ресурсов, войны,",
                      "экологические загрязнения - все убивало Землю."), bg.collider_top_1),
          (stolberg, ("Мы отправимся в прошлое, в начало времен человеческой цивилизации, дабы",
                      "захватить Землю, не уничтожая ее и сохраняя редкие виды минералов и животных.",
                      "Основным источником питания будут Абобы ос."), bg.collider_top_1),
          (stolberg, ("Таким образом, человечество к этому моменту будет жить в мире, размножаться до",
                      "бесконечного количества и заселяться на другие планеты, а может, галактики."),
           bg.collider_top_1),
          (vasisa, "Говорит представитель страны, которая потрясла пробиркой и развязала войну.", bg.collider_top_1),
          (stolberg, "Все понятно с тобой. Тебя уже не излечить.", bg.collider_top_1),
          (stolberg, "Вызывайте негроминаторов!", bg.collider_top_1),
          (stolberg, "… ", bg.collider_top_1),
          (stolberg, ("ЧТО!? НЕТ! КОНВЕЙЕР ОТКЛЮЧЕН?! ПОЧЕМУ ДО СИХ ПОР",
                      "НИКТО НЕ ВЗЯЛСЯ ЗА ЕГО ПОЧИНКУ?"), bg.collider_top_1),
          (stolberg, "КАКОЙ ЕЩЕ ПЕЛЬМЕНЬ?", bg.collider_top_1)],
         [(stolberg, "ПОХОЖЕ ПРИДЕТСЯ ВСЕ ДЕЛАТЬ САМОМУ.", bg.collider_top_1),
          (None, ("Столберг вставил себе Абобу ос. Он превратился в огромный танк.",
                  "Мощным выстрелом он попал по Васисе и отключил модуль невидимости. "), bg.collider_top_1)]
         ],

        # 53
        [[(None, ("Столберг был побежден. Абоба ос который был предназначен для",
                  "зарядки портала, разбушевался."), bg.collider_top_2),
          (vasisa, "Похоже Столберг был связан с ним. Нужно быстрее его отключить! ", bg.collider_top_2),
          (vasisa, "Нет! Не получается!", bg.collider_top_2),
          (bt25, "Кто ты?", bg.collider_top_2)],
         [(vasisa, "Помоги мне отключить Абобу! Для этого кто-то должен прыгнуть туда.", bg.collider_top_2),
          (bt25, ("Точно не я. Я не подведу своих оставшихся друзей,",
                  "которые до сих пор держат оборону."), bg.collider_top_2),
          (vasisa, "Тогда наша судьба решится здесь.", bg.collider_top_2)]
         ],
        # 54
        [[(vasisa, "НЕТ!", bg.collider_top_2),
          (bt25, "Останови эту машину!", bg.collider_top_2),
          (vasisa, "Хорошо. Пожертвовать собой во благо народа. Может, это моя судьба.", bg.collider_top_2),
          (None, "Васиса прыгнула в сферу ускоренной Абобы.", bg.collider_top_2),
          (bt25, "Что происходит?", bg.collider_top_1),
          (vasisa_in_sphere, "Я... Я все вижу... Всю временную линию...", bg.collider_top_1),
          (bt25, "Что?", bg.collider_top_1),
          (vasisa_in_sphere, "Ты должен остановить все это, Камиль.", bg.collider_top_1),
          (bt25, "Как ты узнала?", bg.collider_top_1),
          (vasisa_in_sphere, ("Я вижу все что было до того, как Моисеев прыгнул в портал. Именно тогда",
                              "был произведен первый толчок Энергии в прошлое, а не как в 2023.",
                              "Похоже за Моисеевым прыгнул и ОН."), bg.collider_top_1),
          (vasisa_in_sphere, "Остановии Его.", bg.collider_top_1),
          (vasisa_in_sphere, "Возьми пушку Столберга. Затем заходи в портал...", bg.collider_top_1),
          (bt25, "Похоже придется делать все самому...", bg.collider_top_1),
          (vasisa_in_sphere, "И будь готов... Это твой финальный акт.", bg.collider_top_1)],
         [(pau, "ТЕБЕ НЕ УЙТИ", bg.portal_albina),
          (moiseev_ten, "Покойся с миром. Герой)", bg.portal_albina),
          (None, "Моисеев зашел в портал. ", bg.portal_albina),
          (
          None, "Пау, взлетая на паутине, стреляет в и так ползущую по полу к порталу Альбину и... ", bg.portal_albina),
          (None, "ВЫСТРЕЛ!", bg.portal_albina),
          (bt25, "Oстановись!", bg.portal_albina),
          (pau, "Камиль? Зачем ты это сделал, друг?", bg.portal_albina),
          (bt25, "Дай Альбине зайти в портал и, быть может, мы сможем избавиться от негроминаторов!", bg.portal_albina),
          (pau, "Что за чушь ты несешь? Во всем виноват Моисеев! Я должен остановить его!", bg.portal_albina),
          (bt25, "Нет! Тогда все повториться вновь!", bg.portal_albina),
          (pau, "Похоже Моисеев и тебе мозги промыл. Я просто обязан спасти мир.", bg.portal_albina),
          (None, "Пау, дабы показать, что он не на стороне Камиля раздавил голову Альбине. ", bg.portal),
          (pau, "Все закончится здесь.", bg.portal_final_battle)]
         ],
        # 55 (, "", bg.),
        [[],
         []
         ],
    ]
    return texts
